# RDW Info
- platform: rdw
  name: !secret car_name
  plate: !secret car_plate
  dateformat: '%d %b %Y'
  sensors:
    - expdate
    - insured
    - recall

# Gas Prices
- platform: scrape
  resource: !secret gas_station_1_url
  name: Gas station 1 Euro95
  select: '#station-prijzen > tbody > tr:nth-child(3) > td.literprijs'
  value_template: '{{ ((value.split("€")[1]) | replace(",", ".")) }}'
  unit_of_measurement: "€"
  scan_interval: 3600

- platform: scrape
  resource: !secret gas_station_2_url
  name: Gas station 2 Euro95
  select: '.station-price-content:nth-of-type(1) > span:nth-of-type(2)'
  value_template: '{{ ((value.split("€")[1]) | replace(",", ".")) }}'
  unit_of_measurement: "€"
  scan_interval: 3600

- platform: scrape
  resource: !secret gas_station_2_url
  name: Gas station 2 BlueOne
  select: '.station-price-content:nth-of-type(2) > span:nth-of-type(2)'
  value_template: '{{ ((value.split("€")[1]) | replace(",", ".")) }}'
  unit_of_measurement: "€"
  scan_interval: 3600

- platform: scrape
  resource: !secret gas_station_3_url
  name: Gas station 3 Euro95
  select: '#euro95 > div.pump_price > span.price'
  unit_of_measurement: "€"
  scan_interval: 3600

# Waze
- platform: waze_travel_time
  origin: !secret home_coordinates
  destination: !secret person_one_work_coordinates
  region: 'EU'
  name: Person one drive Home to Work

- platform: waze_travel_time
  origin: !secret person_one_work_coordinates
  destination: !secret home_coordinates
  region: 'EU'
  name: Person one drive Work to Home

- platform: waze_travel_time
  origin: !secret home_coordinates
  destination: !secret person_two_work_coordinates
  region: 'EU'
  name: Person two drive Home to Work

- platform: waze_travel_time
  origin: !secret person_two_work_coordinates
  destination: !secret home_coordinates
  region: 'EU'
  name: Person two drive Work to Home

- platform: nederlandse_spoorwegen
  email: !secret ns_email
  password: !secret ns_password
  routes:
    - name: Person one train Home to Work
      from: !secret home_train_station
      to: !secret person_one_work_train_station
    - name: Person one train Work to Home
      from: !secret person_one_work_train_station
      to: !secret home_train_station
