homeassistant:
  customize: !include customize.yaml

hue:
  bridges:
    - host: 10.0.221.30
      filename: philips-hue.conf

yeelight:
  devices:
    10.0.221.37:
      name: Ledstrip Black Cabinet
      transition: 1000
    10.0.221.39:
      name: Ledstrip Kitchen Cabinet
      transition: 1000
    10.0.221.38:
      name: Ledstrip Large Bedroom
      transition: 1000

binary_sensor: !include binary_sensor.yaml
automation: !include_dir_merge_list automation/
input_boolean: !include boolean.yaml
input_number: !include_dir_merge_named input_number/
light: !include light.yaml
script: !include_dir_merge_named script/
