- platform: template
  sensors:
    hw_dark_enough:
      value_template: >-
        {{ states('sensor.motion_hallway_stairs_illuminance_lux')|int <= states('input_number.hw_illuminance_threshold')|int }}

    toilet_dark_enough:
      value_template: >-
        {{ states('sensor.motion_toilet_illuminance')|int <= 400 }}

    sa_dark_enough:
      value_template: >-
        {{ states('sensor.motion_sitting_area_screen_illuminance_lux')|int <= states('input_number.sa_illuminance_threshold')|int }}

    kitchen_dark_enough:
      value_template: >-
        {{ states('sensor.motion_kitchen_back_illuminance_lux')|int <= states('input_number.kitchen_illuminance_threshold')|int }}

    co_dark_enough:
      value_template: >-
        {{ states('sensor.motion_corridor_illuminance_lux')|int <= states('input_number.co_illuminance_threshold')|int }}

    mb_dark_enough:
      value_template: >-
        {{ states('sensor.motion_master_bedroom_illuminance')|int <= 15 }}        

    bathroom_dark_enough:
      value_template: >-
        {{ states('sensor.motion_bathroom_back_illuminance')|int <= 100 }}

    lb_dark_enough:
      value_template: >-
        {{ states('sensor.motion_large_bedroom_illuminance')|int <= 15 }}

    sb_dark_enough:
      value_template: >-
        {{ states('sensor.motion_small_bedroom_illuminance')|int <= 15 }}

    attic_dark_enough:
      value_template: >-
        {{ states('sensor.0x00158d00036b62d0_illuminance')|int <= 100 }}

    office_dark_enough:
      value_template: >-
        {{ states('sensor.motion_office_back_illuminance')|int <= states('input_number.office_illuminance_threshold')| int }}

    exterior_dark_enough:
      value_template: >-
        {{ states('sensor.motion_backyard_illuminance_lux')|int <= states('input_number.ex_illuminance_threshold')| int }}

    front_of_property_dark_enough:
      value_template: >-
        {{ states('sensor.motion_hallway_stairs_illuminance_lux')|int <= states('input_number.front_of_property_illuminance_threshold')| int }}

    back_of_property_dark_enough:
      value_template: >-
        {{ states('sensor.motion_backyard_illuminance_lux')|int <= states('input_number.back_of_property_illuminance_threshold')| int }}

    # hw_eligable_for_light:
    #   value_template: >-
    #     {{ is_state('binary_sensor.hw_motion_detected', 'on')
    #         and is_state('binary_sensor.hw_dark_enough', 'on') }}

    # toilet_eligable_for_light:
    #   value_template: >-
    #     {{ is_state('binary_sensor.toilet_motion_detected', 'on')
    #         and is_state('binary_sensor.toilet_dark_enough', 'on') }}

    # sa_eligable_for_light:
    #   value_template: >-
    #     {{ is_state('binary_sensor.sa_motion_detected', 'on')
    #         and is_state('binary_sensor.sa_dark_enough', 'on') }}  
      
    # kitchen_eligable_for_light:
    #   value_template: >-
    #     {{ is_state('binary_sensor.kitchen_motion_detected', 'on')
    #         and is_state('binary_sensor.kitchen_dark_enough', 'on') }}

    # co_eligable_for_light:
    #   value_template: >-
    #     {{ is_state('binary_sensor.co_motion_detected', 'on')
    #         and is_state('binary_sensor.co_dark_enough', 'on') }}

    # bathroom_eligable_for_light:
    #   value_template: >-
    #     {{ is_state('binary_sensor.bathroom_motion_detected', 'on')
    #         and is_state('binary_sensor.bathroom_dark_enough', 'on') }}

    # attic_eligable_for_light:
    #   value_template: >-
    #     {{ is_state('binary_sensor.attic_motion_detected', 'on')
    #         and is_state('binary_sensor.attic_dark_enough', 'on') }}

    # office_eligable_for_light:
    #   value_template: >-
    #     {{ is_state('binary_sensor.office_motion_detected', 'on')
    #         and is_state('binary_sensor.office_dark_enough', 'on') }}

    # exterior_eligable_for_light:
    #   value_template: >-
    #     {{ is_state('binary_sensor.exterior_dark_enough', 'on') }}