- platform: template
  sensors:
    sa_dark_enough:
      value_template: >-
        {{ states('sensor.hue_motion_sensor_sitting_area_illuminance')|float < states('input_number.sa_illuminance_threshold')| int }}

    kitchen_dark_enough:
      value_template: >-
        {{ states('sensor.hue_motion_sensor_kitchen_illuminance')|float < states('input_number.kitchen_illuminance_threshold')| int }}

    hw_dark_enough:
      value_template: >-
        {{ states('sensor.hue_motion_sensor_hallway_stairs_illuminance')|float < 10 }}

    co_dark_enough:
      value_template: >-
        {{ states('sensor.hue_motion_sensor_corridor_illuminance')|float < 10 }}

    bathroom_dark_enough:
      value_template: >-
        {{ states('sensor.0x00158d000349234a_illuminance')|float < 100 }}

    attic_dark_enough:
      value_template: >-
        {{ states('sensor.0x00158d00036b62d0_illuminance')|float < 100 }}

    office_dark_enough:
      value_template: >-
        {{ states('sensor.0x00158d0004499f26_illuminance')|float < 15 }}

    exterior_dark_enough:
      value_template: >-
        {{ states('sensor.hue_motion_sensor_sitting_area_illuminance')|float < 10 }}
