- platform: template
  sensors:
    hw_dark_enough:
      value_template: >-
        {{ states('sensor.motion_hallway_stairs_illuminance_lux')|int <= states('input_number.hw_illuminance_threshold')|int }}

    toilet_dark_enough:
      value_template: >-
        {{ states('sensor.motion_toilet_illuminance')|int <= 400 }}

    sa_dark_enough:
      value_template: >-
        {{ states('sensor.motion_sitting_area_screen_illuminance_lux')|int <= states('input_number.sa_illuminance_threshold')|int }}

    kitchen_dark_enough:
      value_template: >-
        {{ states('sensor.motion_kitchen_back_illuminance_lux')|int <= states('input_number.kitchen_illuminance_threshold')|int }}

    co_dark_enough:
      value_template: >-
        {{ states('sensor.motion_corridor_illuminance_lux')|int <= states('input_number.co_illuminance_threshold')|int }}

    mb_dark_enough:
      value_template: >-
        {{ states('sensor.motion_master_bedroom_illuminance')|int <= 15 }}        

    bathroom_dark_enough:
      value_template: >-
        {{ states('sensor.motion_bathroom_back_illuminance')|int <= 100 }}

    lb_dark_enough:
      value_template: >-
        {{ states('sensor.motion_large_bedroom_closet_illuminance')|int <= 15 }}

    sb_dark_enough:
      value_template: >-
        {{ states('sensor.motion_small_bedroom_illuminance')|int <= 15 }}

    attic_dark_enough:
      value_template: >-
        {{ states('sensor.motion_attic_stairs_illuminance')|int <= 100 }}

    office_dark_enough:
      value_template: >-
        {{ states('sensor.motion_office_back_illuminance')|int <= states('input_number.office_illuminance_threshold')| int }}

    exterior_dark_enough:
      value_template: >-
        {{ states('sensor.motion_backyard_illuminance_lux')|int <= states('input_number.ex_illuminance_threshold')| int }}

    front_of_property_dark_enough:
      value_template: >-
        {{ states('sensor.motion_hallway_stairs_illuminance_lux')|int <= states('input_number.front_of_property_illuminance_threshold')| int }}

    back_of_property_dark_enough:
      value_template: >-
        {{ states('sensor.motion_backyard_illuminance_lux')|int <= states('input_number.back_of_property_illuminance_threshold')| int }}

    time_for_dim_scenes:
      value_template: >-
        {{ is_state('binary_sensor.early_night', 'on')
           or is_state('binary_sensor.late_night', 'on') }}

    sa_allow_media_status_scene_switching:
      value_template: >-
        {{ is_state('binary_sensor.late_evening', 'on')
           or is_state('binary_sensor.early_night', 'on')
           or is_state('binary_sensor.late_night', 'on') }}

    allow_exterior_lights:
      value_template: >-
        {{ is_state('binary_sensor.late_afternoon', 'on')
           or is_state('binary_sensor.early_evening', 'on')
           or is_state('binary_sensor.late_evening', 'on')
           or is_state('binary_sensor.early_night', 'on')
           or is_state('binary_sensor.early_morning', 'on') }}

    allow_turning_off_bedroom_lights:
      value_template: >-
        {{ is_state('binary_sensor.late_morning', 'on')
           or is_state('binary_sensor.early_afternoon', 'on')
           or is_state('binary_sensor.late_afternoon', 'on')
           or is_state('binary_sensor.early_evening', 'on') }}

- platform: tod
  name: bathroom_dim_scene
  after: '22:59'
  before: '6:29'