- platform: flux_led
  devices:
    10.0.221.31:
      name: Ledstrip TV Cabinet
      protocol: 'ledenet'
      mode: "rgbw"

- platform: group
  name: LG | HW | All
  entities:
    - light.0x0017880103ea3a60_light

- platform: group
  name: LG | Toilet | All
  entities:
    - light.0x086bd7fffe2b8f58_light

- platform: group
  name: LG | SA | LED strips
  entities:
    - light.ledstrip_tv_cabinet
    - light.ledstrip_black_cabinet

- platform: group
  name: LG | LR | LED strips
  entities:
    - light.lg_sa_led_strips
    - light.ledstrip_kitchen_cabinet

- platform: group
  name: LG | SA | All
  entities:
    - light.0x00178801081af093_light
    - light.hue_go_closet_l
    - light.hue_go_closet_r
    - light.0x00178801089f827b_light
    - light.hue_iris_tv_cabinet
    - light.hue_candle_salt_lamp
    - light.lg_sa_led_strips

- platform: group
  name: LG | Kitchen | Table
  entities:
    - light.0x00178801081b61c2_light
    - light.0x00178801081b3c89_light

- platform: group
  name: LG | Kitchen | Counter
  entities:
    - light.hue_spot_kitchen_counter_1
    - light.hue_spot_kitchen_counter_2
    - light.hue_spot_kitchen_counter_3
    - light.hue_spot_kitchen_counter_4

- platform: group
  name: LG | Kitchen | All
  entities:
    - light.lg_kitchen_table
    - light.lg_kitchen_counter
    - light.ledstrip_kitchen_cabinet

- platform: group
  name: LG | LR | All
  entities:
    - light.lg_sa_all
    - light.lg_kitchen_all

- platform: group
  name: LG | EX | All
  entities:
    - light.0x086bd7fffe035d36_light
    - light.0x000b57fffee35b50_light

- platform: group
  name: LG | MB | All
  entities:
    - light.0x90fd9ffffeea4e5e_light

- platform: group
  name: LG | SB | All
  entities:
    - light.0x00178801023c1a33_light
    - light.dimmable_socket_one

- platform: group
  name: LG | LB | All
  entities:
    - light.0x00178801039d140f_light
    - light.ledstrip_large_bedroom

- platform: group
  name: LG | CO | All
  entities:
    - light.0x00178801030a3dde_light

- platform: group
  name: LG | Bathroom | All
  entities:
    - light.hue_candle_bathroom_l
    - light.hue_bulb_bathroom_r

- platform: group
  name: LG | Attic | All
  entities:
    - light.0x000b3cfffefab3f6_light
    - light.0x086bd7fffe020f14_light

- platform: group
  name: LG | Office | All
  entities:
    - light.0x00178801023c1b25_light
    - light.0x0017880102460013_light
