# - platform: flux_led
#   devices:
#     10.0.221.31:
#       name: Ledstrip TV Cabinet
#       protocol: 'ledenet'
#       mode: "rgbw"

- platform: group
  name: LG | HW | All
  entities:
    - light.0x0017880103ea3a60_light

- platform: group
  name: LG | Toilet | All
  entities:
    - light.0x086bd7fffe2b8f58_light

- platform: group
  name: LG | SA | LED strips
  entities:
    - light.ledstrip_tv_cabinet
    - light.ledstrip_black_cabinet

- platform: group
  name: LG | LR | LED strips
  entities:
    - light.lg_sa_led_strips
    - light.ledstrip_kitchen_cabinet

- platform: group
  name: LG | SA | All
  entities:
    - light.lg_sa_filament_bulbs
    - light.lg_sa_white_closet 
    - light.lg_sa_tv_cabinet
    - light.lg_sa_led_strips

- platform: group
  name: LG | Kitchen | All
  entities:
    - light.lg_kitchen_table
    - light.lg_kitchen_counter
    - light.ledstrip_kitchen_cabinet

- platform: group
  name: LG | LR | All
  entities:
    - light.lg_sa_all
    - light.lg_kitchen_all

- platform: group
  name: LG | MB | All
  entities:
    - light.0x90fd9ffffeea4e5e_light
    - light.ledstrip_undecided

- platform: group
  name: LG | SB | All
  entities:
    - light.lg_sb_zigbee
    - light.dimmable_socket_one

- platform: group
  name: LG | LB | All
  entities:
    - light.lg_lb_zigbee
    - light.ledstrip_large_bedroom

- platform: group
  name: LG | CO | All
  entities:
    - light.0x00178801030a3dde_light

- platform: mqtt
  schema: json
  name: lg_sa_tv_cabinet
  command_topic: "zigbee2mqtt/lg_sa_tv_cabinet/set"
  state_topic: "zigbee2mqtt/lg_sa_tv_cabinet"
  color_temp: true
  brightness: true
  rgb: true

- platform: mqtt
  schema: json
  name: lg_sa_filament_bulbs
  command_topic: "zigbee2mqtt/lg_sa_filament_bulbs/set"
  state_topic: "zigbee2mqtt/lg_sa_filament_bulbs"
  color_temp: true
  brightness: true
  rgb: false

- platform: mqtt
  schema: json
  name: lg_sa_white_closet
  command_topic: "zigbee2mqtt/lg_sa_white_closet/set"
  state_topic: "zigbee2mqtt/lg_sa_white_closet"
  color_temp: true
  brightness: true
  rgb: true

- platform: mqtt
  schema: json
  name: lg_kitchen_counter
  command_topic: "zigbee2mqtt/lg_kitchen_counter/set"
  state_topic: "zigbee2mqtt/lg_kitchen_counter"
  color_temp: true
  brightness: true
  rgb: false

- platform: mqtt
  schema: json
  name: lg_kitchen_table
  command_topic: "zigbee2mqtt/lg_kitchen_table/set"
  state_topic: "zigbee2mqtt/lg_kitchen_table"
  color_temp: true
  brightness: true
  rgb: false

- platform: mqtt
  schema: json
  name: lg_bathroom_all
  command_topic: "zigbee2mqtt/lg_bathroom_all/set"
  state_topic: "zigbee2mqtt/lg_bathroom_all"
  color_temp: true
  brightness: true
  rgb: true

- platform: mqtt
  schema: json
  name: lg_lb_zigbee
  command_topic: "zigbee2mqtt/lg_lb_zigbee/set"
  state_topic: "zigbee2mqtt/lg_lb_zigbee"
  color_temp: true
  brightness: true
  rgb: true

- platform: mqtt
  schema: json
  name: lg_sb_zigbee
  command_topic: "zigbee2mqtt/lg_sb_zigbee/set"
  state_topic: "zigbee2mqtt/lg_sb_zigbee"
  color_temp: true
  brightness: true
  rgb: true

- platform: mqtt
  schema: json
  name: lg_attic_all
  command_topic: "zigbee2mqtt/lg_attic_all/set"
  state_topic: "zigbee2mqtt/lg_attic_all"
  color_temp: true
  brightness: true
  rgb: false

- platform: mqtt
  schema: json
  name: lg_office_all
  command_topic: "zigbee2mqtt/lg_office_all/set"
  state_topic: "zigbee2mqtt/lg_office_all"
  color_temp: true
  brightness: true
  rgb: true

- platform: mqtt
  schema: json
  name: lg_ex_all
  command_topic: "zigbee2mqtt/lg_ex_all/set"
  state_topic: "zigbee2mqtt/lg_ex_all"
  color_temp: true
  brightness: true
  rgb: false