- platform: template
  sensors:
    hue_motion_sensor_hallway_door_illuminance:
      value_template: "{{ (states('sensor.0x00178801020260c3_illuminance') }}"
      unit_of_measurement: Lux

    hue_motion_sensor_hallway_stairs_illuminance:
      value_template: "{{ (states('sensor.0x00178801020282bc_illuminance') }}"
      unit_of_measurement: Lux

    hue_motion_sensor_kitchen_illuminance:
      value_template: "{{ (states('sensor.0x0017880102030677_illuminance') }}"
      unit_of_measurement: Lux

    hue_motion_sensor_sitting_area_illuminance:
      value_template: "{{ (states('sensor.0x0017880102026161_illuminance') }}"
      unit_of_measurement: Lux

    hue_motion_sensor_corridor_illuminance:
      value_template: "{{ (states('sensor.0x00178801020357e5_illuminance') }}"
      unit_of_measurement: Lux
