homeassistant:
  customize: !include customize.yaml

binary_sensor: !include binary_sensor.yaml
input_boolean: !include boolean.yaml
camera: !include camera.yaml
automation: !include automation.yaml
# alert: !include alert.yaml
scene: !include scene.yaml
