- id: sec_001
  alias: sec_001
  trigger:
    - platform: state
      entity_id: input_boolean.alarm_armed
      to:
        - 'on'
        - 'off'
  action:
    service: scene.turn_on
    data_template:
      entity_id: >
        {% if trigger.to_state.state == 'on' %}
          scene.setup_security_defaults
        {% elif trigger.to_state.state == 'off' %}
          scene.restore_regular_defaults
        {% endif %}


- id: sec_002
  alias: sec_002
  trigger:
    - platform: state
      entity_id: binary_sensor.simulate_occupancy
      to:
        - 'on'
        - 'off'
  action:
    service: scene.turn_on
    data_template:
      entity_id: >
        {% if trigger.to_state.state == 'on' %}
          scene.simulate_occupancy
        {% elif trigger.to_state.state == 'off' %}
          scene.reset_occupancy_simulation
        {% endif %}


- id: sec_003
  alias: sec_003
  trigger:
    platform: state
    entity_id:
      - binary_sensor.front_door_open
      - binary_sensor.back_door_open
      - binary_sensor.kitchen_window_open
    to: 'on'
    for:
      minutes: 1
  condition:
    condition: state
    entity_id: binary_sensor.aggressive_notifications
    state: 'on'
  action:
    service: notify.send_mail
    data_template:
      title: "{{ state_attr(trigger.entity_id, 'device_class')|upper }} ALERT!: {{ state_attr(trigger.entity_id, 'friendly_name') }} is open"
      message: "Nobody is home but {{ state_attr(trigger.entity_id, 'friendly_name') }} is open!!\n
                Time of detection: {{ now().strftime('%H:%M') }}\n
                Verify it's either closed or should be closed!"
