- id: sec_001
  alias: sec_001
  trigger:
    platform: state
    entity_id: input_boolean.alarm_armed
    to: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.simulate_occupancy


- id: sec_002
  alias: sec_002
  trigger:
    platform: state
    entity_id: input_boolean.alarm_armed
    to: 'off'
  action:
    service: scene.turn_off
    entity_id: scene.reset_occupancy_simulation


- id: sec_003
  alias: sec_003
  trigger:
    platform: state
    entity_id:
      - binary_sensor.front_door_open
      - binary_sensor.back_door_open
      - binary_sensor.kitchen_window_open
    to: 'on'
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: binary_sensor.agressive_notifications
    state: 'on'
  action:
    service: notify.send_mail
    data_template:
      title: "{{ state_attr(trigger.entity_id, 'device_class')|upper }} ALERT!: {{ state_attr(trigger.entity_id, 'friendly_name') }} is open"
      message: "Nobody is home but {{ state_attr(trigger.entity_id, 'friendly_name') }} is open!!\n
                Time of detection: {{ now().strftime('%H:%M') }}\n
                Verify it's either closed or should be closed!"
