- platform: template
  sensors:
    alarm_armed:
      value_template: >-
        {{ is_state('input_boolean.alarm_armed', 'on') }}

    aggressive_notifications:
      value_template: >-
        {{ is_state('input_boolean.aggressive_notifications', 'on') }}

    simulate_occupancy:
      value_template: >-
        {{ is_state('input_boolean.simulate_occupancy', 'on')
           and is_state('binary_sensor.sa_dark_enough', 'on') }}
