- platform: template
  sensors:
    alarm_armed:
      value_template: >-
        {{ is_state('input_boolean.alarm_armed', 'on') }}

    aggressive_notifications:
      value_template: >-
        {{ is_state('input_boolean.aggressive_notifications', 'on') }}

    front_door_open:
      value_template: >-
        {{ is_state('binary_sensor.0x00158d000446eb21_contact', 'on') }}

    kitchen_window_open:
      value_template: >-
        {{ is_state('binary_sensor.0x00158d000446fc0a_contact', 'on') }}

    back_door_open:
      value_template: >-
        {{ is_state('binary_sensor.0x00158d000446f39b_contact', 'on') }}
