- platform: template
  sensors:
    alarm_armed:
      value_template: >-
        {{ is_state('input_boolean.alarm_armed', 'on') }}

    aggressive_notifications:
      value_template: >-
        {{ is_state('input_boolean.aggressive_notifications', 'on') }}
