# - platform: synology
#   url: !secret synology_url
#   username: !secret synology_username
#   password: !secret synology_password
#   timeout: 15
#   verify_ssl: false

- platform: ffmpeg
  name: Dafang
  input: !secret dafang_stream_url

- platform: ffmpeg
  name: Xiaofang 1
  input: !secret xiaofang_1_stream_url

- platform: ffmpeg
  name: Xiaofang 2
  input: !secret xiaofang_2_stream_url
