title: automation_view
icon: mdi:robot
cards:
  - type: custom:monster-card
    show_empty: false
    card:
      type: entities
      title: ALl automations
    filter:
      include:
        - entity_id: "automation.*"
  - type: custom:monster-card
    show_empty: false
    card:
      type: entities
      title: Hallway automations
    filter:
      include:
        - entity_id: "automation.hw*"
  - type: custom:monster-card
    show_empty: false
    card:
      type: entities
      title: Sitting area automations
    filter:
      include:
        - entity_id: "automation.sa*"
  - type: custom:monster-card
    show_empty: false
    card:
      type: entities
      title: Kitchen automations
    filter:
      include:
        - entity_id: "automation.kitchen*"
  - type: custom:monster-card
    show_empty: false
    card:
      type: entities
      title: Corridor automations
    filter:
      include:
        - entity_id: "automation.co*"
  - type: custom:monster-card
    show_empty: false
    card:
      type: entities
      title: Master bedroom automations
    filter:
      include:
        - entity_id: "automation.mb*"
  - type: custom:monster-card
    show_empty: false
    card:
      type: entities
      title: Large bedroom automations
    filter:
      include:
        - entity_id: "automation.large_bedroom*"
  - type: custom:monster-card
    show_empty: false
    card:
      type: entities
      title: Exterior automations
    filter:
      include:
        - entity_id: "automation.ex*"
