title: automation_view
icon: mdi:robot
cards:
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Hallway automations
    filter:
      include:
        - entity_id: "automation.hw*"
        - entity_id: "input_boolean.automation_hw*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Sitting area automations
    filter:
      include:
        - entity_id: "automation.sa*"
        - entity_id: "input_boolean.automation_sa*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Kitchen automations
    filter:
      include:
        - entity_id: "automation.kitchen*"
        - entity_id: "input_boolean.automation_kitchen*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Corridor automations
    filter:
      include:
        - entity_id: "automation.co*"
        - entity_id: "input_boolean.automation_co*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Master bedroom automations
    filter:
      include:
        - entity_id: "automation.mb*"
        - entity_id: "input_boolean.automation_mb*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Large bedroom automations
    filter:
      include:
        - entity_id: "automation.lb*"
        - entity_id: "input_boolean.automation_lb*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Small bedroom automations
    filter:
      include:
        - entity_id: "automation.sb*"
        - entity_id: "input_boolean.automation_sb*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Attic automations
    filter:
      include:
        - entity_id: "automation.attic*"
        - entity_id: "input_boolean.automation_attic*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Office automations
    filter:
      include:
        - entity_id: "automation.office*"
        - entity_id: "input_boolean.automation_office*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Exterior automations
    filter:
      include:
        - entity_id: "automation.ex*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Security automations
    filter:
      include:
        - entity_id: "automation.sec*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Matrix bot automations
    filter:
      include:
        - entity_id: "automation.matrix*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Christmas automations
    filter:
      include:
        - entity_id: "automation.xmas*"
  - type: conditional
    conditions:
      - entity: input_boolean.advanced_config
        state: "on"
    card:
      type: custom:auto-entities
      show_empty: false
      card:
        type: entities
        title: All automations
      filter:
        include:
          - entity_id: "automation.*"
