title: automation_view
icon: mdi:robot
cards:
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: All automations
    filter:
      include:
        - entity_id: "automation.*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Hallway automations
    filter:
      include:
        - entity_id: "automation.hw*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Sitting area automations
    filter:
      include:
        - entity_id: "automation.sa*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Kitchen automations
    filter:
      include:
        - entity_id: "automation.kitchen*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Corridor automations
    filter:
      include:
        - entity_id: "automation.co*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Master bedroom automations
    filter:
      include:
        - entity_id: "automation.mb*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Large bedroom automations
    filter:
      include:
        - entity_id: "automation.lb*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Small bedroom automations
    filter:
      include:
        - entity_id: "automation.sb*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Exterior automations
    filter:
      include:
        - entity_id: "automation.ex*"
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Matrix bot automations
    filter:
      include:
        - entity_id: "automation.matrix*"
