title: Home
views:
  - title: Home
    icon: mdi:home
    cards:
      - type: entities
        entities:
          - sensor.motion_in_hallwaystairs
          - sensor.motion_in_hallwaydoor
          - sensor.motion_in_sitting_area
          - binary_sensor.motion_sensor_sa
          - sensor.motion_in_kitchen
          - sensor.motion_in_corridor
          - binary_sensor.motion_sensor_attic
          - switch.beamer_screen
          - switch.sun_screen
          - cover.attic_shutters
          - sensor.postnl
          - sensor.home_to_work
          - sensor.work_to_home
      - type: weather-forecast
        entity: weather.dark_sky
      - type: entities
        title: Hallway lighting
        show_header_toggle: true
        entities:
          - light.hue__bulb__hallway
      - type: entities
        title: Living room lighting
        show_header_toggle: true
        entities:
          - light.kitchen
          - light.sitting_area
          - light.ledstrip_tv_cabinet
          - light.ledstrip_black_cabinet
      - type: entities
        title: Corridor lighting
        show_header_toggle: true
        entities:
          - light.hue__bulb__corridor
      - type: entities
        title: Exterior lighting
        show_header_toggle: true
        entities:
          - light.front_porch
          - light.backyard
      - type: entities
        title: Living room climate
        show_header_toggle: true
        entities:
          - climate.living_room
          - sensor.temperature_in_hallwaydoor
          - sensor.temperature_in_hallwaystairs
          - sensor.temperature_in_sitting_area
          - sensor.temperature_in_kitchen
      - type: entities
        title: Power Sockets
        show_header_toggle: true
        entities:
          - switch.power_socket_one
          - switch.power_socket_two
          - switch.power_socket_three
          - light.dimmable_socket_one
          - light.dimmable_socket_two
      - type: entities
        title: Programmable switches
        show_header_toggle: true
        entities:
          - switch.programmable_one
          - switch.programmable_two
          - switch.programmable_three
          - switch.programmable_four
          - switch.programmable_five
          - switch.programmable_six
          - switch.programmable_seven
          - switch.programmable_eight
  - title: Ground floor
    icon: mdi:numeric-0-box
    cards:
      - type: entities
        title: Living room lighting
        show_header_toggle: true
        entities:
          - light.kitchen
          - light.sitting_area
          - light.ledstrip_tv_cabinet
          - light.ledstrip_black_cabinet
      - type: entities
        title: Hallway lighting
        show_header_toggle: true
        entities:
          - light.hue__bulb__hallway
      - type: entities
        title: All ground floor lights
        show_header_toggle: true
        entities:
          - light.hue__bulb__kitchen_table__l
          - light.hue__bulb__kitchen_table__r
          - light.hue__spot__kitchen_counter__1
          - light.hue__spot__kitchen_counter__2
          - light.hue__spot__kitchen_counter__3
          - light.hue__spot__kitchen_counter__4
          - light.hue__bulb__standing_lamp
          - light.hue__iris__tv_cabinet
          - light.hue__go__closet__l
          - light.hue__go__closet__r
          - light.ledstrip_tv_cabinet
          - light.ledstrip_black_cabinet
          - light.hue__bulb__hallway
          - light.dimmable_socket_one
          - light.dimmable_socket_two
      - type: entities
        title: Ground floor switches
        show_header_toggle: true
        entities:
          - switch.power_socket_one
          - switch.power_socket_two
          - switch.power_socket_three
          - light.dimmable_socket_one
          - light.dimmable_socket_two
          - switch.beamer_screen
      - type: entities
        title: Ground floor automations
        show_header_toggle: true
        entities:
          - automation.hw__motion__lights_on
          - automation.hw__motion__lights_off
          - automation.sa__no_media
          - automation.sa__media_playing__state_one
          - automation.sa__media_playing__state_two
          - automation.sa__time__lights_off
          - automation.sa__motion__christmas_tree_on
          - automation.sa__motion__christmas_tree_off
          - automation.kitchen__time__lights_on
          - automation.kitchen__time__lights_off
      - type: entities
        title: Ground floor doors and windows
        show_header_toggle: true
        entities:
          - binary_sensor.front_door
  - !include first_floor.yaml
