title: Bier Estates
resources:
- url: !file /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js
  type: js
- url: !file /local/custom-lovelace/lovelace-auto-entities/auto-entities.js
  type: module
- url: !file /local/custom-lovelace/lovelace-swipe-navigation/swipe-navigation.js
  type: js
- url: !file /local/custom-lovelace/lovelace-bar-card/bar-card.js
  type: js
- url: !file /local/custom-lovelace/lovelace-card-tools/card-tools.js
  type: js
- url: !file /local/custom-lovelace/lovelace-fold-entity-row/fold-entity-row.js
  type: js
- url: !file /local/custom-lovelace/lovelace-mini-graph-card/mini-graph-card-bundle.js
  type: js
- url: !file /local/custom-lovelace/lovelace-mini-media-player/mini-media-player-bundle.js
  type: js
- url: !file /local/custom-lovelace/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js
  type: module

views:
  - !include home.yaml
  - !include ground_floor.yaml
  - !include first_floor.yaml
  - !include attic.yaml
  - !include exterior.yaml
  - !include people.yaml
  - !include plants.yaml
  - !include media.yaml
  - !include scenes.yaml
  - !include security.yaml
  - !include network.yaml
  - !include finance.yaml
  - !include automation.yaml
  - !include overrides.yaml
