title: Bier Estates
# Include external resources
resources:
- url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js
  type: js
views:
  - !include home.yaml
  - !include ground_floor.yaml
  - !include first_floor.yaml
  - !include attic.yaml
  - !include exterior.yaml
  - !include plants.yaml
  - !include media.yaml
  - !include security.yaml
  - !include network.yaml
  - !include automation.yaml
  - !include overrides.yaml
