title: Bier Estates
views:
  - title: Home
    icon: mdi:home
    cards:
      - type: entities
        entities:
          - sensor.motion_in_hallwaystairs
          - sensor.motion_in_hallwaydoor
          - sensor.motion_in_sitting_area
          - binary_sensor.motion_sensor_sa
          - sensor.motion_in_kitchen
          - sensor.motion_in_corridor
          - binary_sensor.motion_sensor_attic
          - switch.beamer_screen
          - switch.sun_screen
          - cover.attic_shutters
          - sensor.postnl
          - sensor.home_to_work
          - sensor.work_to_home
      - type: weather-forecast
        entity: weather.dark_sky
      - type: entities
        title: Hallway lighting
        show_header_toggle: true
        entities:
          - light.hue__bulb__hallway
      - type: entities
        title: Living room lighting
        show_header_toggle: true
        entities:
          - light.kitchen
          - light.sitting_area
          - light.ledstrip_tv_cabinet
          - light.ledstrip_black_cabinet
      - type: entities
        title: Corridor lighting
        show_header_toggle: true
        entities:
          - light.hue__bulb__corridor
      - type: entities
        title: Exterior lighting
        show_header_toggle: true
        entities:
          - light.front_porch
          - light.backyard
      - type: entities
        title: Living room climate
        show_header_toggle: true
        entities:
          - climate.living_room
          - sensor.temperature_in_hallwaydoor
          - sensor.temperature_in_hallwaystairs
          - sensor.temperature_in_sitting_area
          - sensor.temperature_in_kitchen
      - type: entities
        title: Power Sockets
        show_header_toggle: true
        entities:
          - switch.power_socket_one
          - switch.power_socket_two
          - switch.power_socket_three
          - light.dimmable_socket_one
          - light.dimmable_socket_two
      - type: entities
        title: Programmable switches
        show_header_toggle: true
        entities:
          - switch.programmable_one
          - switch.programmable_two
          - switch.programmable_three
          - switch.programmable_four
          - switch.programmable_five
          - switch.programmable_six
          - switch.programmable_seven
          - switch.programmable_eight
  - !include ground_floor.yaml
  - !include first_floor.yaml
  - !include attic.yaml
  - !include exterior.yaml
  - !include media.yaml
  - !include security.yaml
  - !include automation.yaml
  - !include overrides.yaml
