title: Bier Estates
# Include external resources
resources:
- url: /local/tracker-card.js?v=0.1.5
  type: js
- url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.3.3
  type: js
- url: /local/custom-lovelace/monster-card/monster-card.js?v=0.2.3
  type: js
views:
  - !include home.yaml
  - !include ground_floor.yaml
  - !include first_floor.yaml
  - !include attic.yaml
  - !include exterior.yaml
  - !include plants.yaml
  - !include media.yaml
  - !include security.yaml
  - !include network.yaml
  - !include automation.yaml
  - !include overrides.yaml
