title: Security
icon: mdi:cctv
cards:
  - type: picture-entity
    title: Foscam1
    entity: camera.foscam1
    camera_image: camera.foscam1
    show_info: true
    tap_action: dialog
  - type: picture-entity
    title: XiaoFang1
    entity: camera.xiaofang1
    camera_image: camera.xiaofang1
    show_info: true
    tap_action: dialog
  - type: picture-entity
    title: XiaoFang2
    entity: camera.xiaofang2
    camera_image: camera.xiaofang2
    show_info: true
    tap_action: dialog
