- alias: EX | State | Lights on
  trigger:
    platform: state
    entity_id: binary_sensor.exterior_dark_enough
    to: 'on'
  condition:
      condition: time
      after: '16:00:00'
      before: '03:30:00'
  action:
    - service: scene.turn_on
      entity_id: scene.ex_relax
    - service: switch.turn_on
      entity_id: switch.0x000d6ffffea6e967_switch
