- alias: EX | State | Lights on
  trigger:
    platform: state
    entity_id: binary_sensor.exterior_dark_enough
    to: 'on'
  condition:
      condition: time
      before: '3:30:00'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Exterior"
        scene_name: "EX | Relax"
    - service: switch.turn_on
      entity_id: switch.power_socket_three
