- alias: EX | State | Lights on
  trigger:
    platform: state
    entity_id: binary_sensor.exterior_dark_enough
    to: 'on'
  condition:
      condition: time
      after: '18:00:00'
      before: '03:30:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.lg_ex_all
        brightness_pct: 50
        kelvin: 2700
    - service: switch.turn_on
      entity_id: switch.0x000d6ffffea6e967_switch
