- alias: "EX | Time | Lights off"
  trigger:
    - platform: time
      at: '3:30:00'
  action:
    - service: light.turn_off
      entity_id: light.lg_ex_all
    - service: switch.turn_off
      entity_id: switch.0x000d6ffffea6e967_switch
