- alias: "EX | Time | Lights on"
  trigger:
    - platform: time
      at: '17:30:00'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Exterior"
        scene_name: "EX | Relax"
