- alias: 'React to an introduction'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: introduction
  action:
    service: notify.matrix_notify
    data_template:
      message: "My name is Hassi-o, servant of men ruler of tech."


- alias: 'Turn on all the things'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: light_em_up
  action:
    - service: switch.turn_on
      entity_id: switch.power_socket_one
    - service: switch.turn_on
      entity_id: switch.power_socket_two
    - service: switch.turn_on
      entity_id: switch.power_socket_three
    - service: light.turn_on
      data:
        entity_id: light.dimmable_socket_one
        brightness: 35
    - service: light.turn_on
      data:
        entity_id: light.dimmable_socket_two
    - service: hue.hue_activate_scene
      data:
        group_name: "Kitchen"
        scene_name: "Kitchen | Relax"
    - service: hue.hue_activate_scene
      data:
        group_name: "Kitchen"
        scene_name: "Kitchen | Relax"
    - service: script.turn_on
      entity_id: script.scene_not_watching_tv
    - service: notify.matrix_notify
      data:
        message: "Shining bright like a diamond!"


- alias: 'React to Cut socket one'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_socket_one
  action:
    - service: switch.turn_off
      entity_id: switch.power_socket_one
    - service: notify.matrix_notify
      data:
        message: "Socket one killed!"


- alias: 'React to !cut_the_power'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_the_power
  action:
    - service: switch.turn_off
      entity_id: switch.power_socket_one
    - service: switch.turn_off
      entity_id: switch.power_socket_two
    - service: notify.matrix_notify
      data:
        message: "I've cut the power as you requested!"


- alias: 'React to !reel_in_the_sunscreen'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: reel_in_the_sunscreen
  action:
    - service: switch.turn_off
      entity_id: switch.sun_screen
    - service: notify.matrix_notify
      data:
        message: "As you wish! May the Sun shine freely!"
