- alias: 'React to !cut_the_power'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_the_power
  action:
    - service: switch.turn_off
      entity_id: switch.power_socket_one
    - service: switch.turn_off
      entity_id: switch.power_socket_two
    - service: notify.matrix_notify
      data:
        message: "I've cut the power as you requested!"

    
- alias: 'React to an introduction'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: introduction
  action:
    service: notify.matrix_notify
    data_template:
      message: "My name is Hassi-o, servant of men ruler of tech."

