- alias: 'Matrix | React to an introduction'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: introduction
  action:
    service: notify.matrix_notify
    data_template:
      message: "My name is Hassi-o, servant of men ruler of tech."


- alias: 'Matrix | Turn on all the things'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: light_em_up
  action:
    - service: switch.turn_ion
      entity_id: switch.power_socket_one
    - service: switch.turn_on
      entity_id: switch.power_socket_two
    - service: switch.turn_on
      entity_id: switch.power_socket_three
    - service: light.turn_on
      data:
        entity_id: light.dimmable_socket_one
        brightness: 35
    - service: light.turn_on
      data:
        entity_id: light.dimmable_socket_two
    - service: hue.hue_activate_scene
      data:
        group_name: "Kitchen"
        scene_name: "Kitchen | Relax"
    - service: hue.hue_activate_scene
      data:
        group_name: "Kitchen"
        scene_name: "Kitchen | Relax"
    - service: script.turn_on
      entity_id: script.scene_not_watching_tv
    - service: notify.matrix_notify
      data:
        message: "Shining bright like a diamond!"


- alias: 'Matrix | React to Cut socket one'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_socket_one
  action:
    - service: switch.turn_off
      entity_id: switch.power_socket_one
    - service: notify.matrix_notify
      data:
        message: "Socket one killed!"


- alias: 'Matrix | React to Cut socket two'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_socket_two
  action:
    - service: switch.turn_off
      entity_id: switch.power_socket_two
    - service: notify.matrix_notify
      data:
        message: "Socket two killed!"


- alias: 'Matrix | React to Cut socket three'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_socket_three
  action:
    - service: switch.turn_off
      entity_id: switch.power_socket_three
    - service: notify.matrix_notify
      data:
        message: "Socket three killed!"


- alias: 'Matrix | React to Cut all power'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_all_power
  action:
    - service: switch.turn_off
      entity_id: switch.power_socket_one
    - service: switch.turn_off
      entity_id: switch.power_socket_two
    - service: switch.turn_off
      entity_id: switch.power_socket_three
    - service: light.turn_off
      data:
        entity_id: light.dimmable_socket_one
    - service: light.turn_off
      data:
        entity_id: light.dimmable_socket_two
    - service: notify.matrix_notify
      data:
        message: "I've cut the power as you requested!"


- alias: 'Matrix | React to !reel_in_the_sunscreen'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: reel_in_the_sunscreen
  action:
    - service: switch.turn_off
      entity_id: switch.sun_screen
    - service: notify.matrix_notify
      data:
        message: "As you wish! May the Sun shine freely!"


- alias: 'Matrix | React to Cheapest local gas'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: show_gas_prices
  action:
    - service: notify.matrix_notify
      data:
        message: "Toda's gas prices: \n Ti: {{ sensor.gas_station_1_euro95 }} \n Fi: {{ sensor.gas_station_2_euro95 }} \n Ta: {{ sensor.gas_station_3_euro95 }}"
