- platform: coingecko
  scan_interval: 5
  wallets:
    - market: !secret coin1_token
      amount: !secret coin1_owned
      costs: !secret coin1_paid
    - market: !secret coin2_token
      amount: !secret coin2_owned
      costs: !secret coin2_paid
    - market: !secret coin3_token
      amount: !secret coin3_owned
      costs: !secret coin3_paid
    - market: !secret coin4_token
      amount: !secret coin4_owned
      costs: !secret coin4_paid
    - market: !secret coin5_token
      amount: !secret coin5_owned
      costs: !secret coin5_paid
    - market: !secret coin6_token
      amount: !secret coin6_owned
      costs: !secret coin6_paid
    - market: !secret coin7_token
      amount: !secret coin7_owned
      costs: !secret coin7_paid
    - market: !secret coin8_token
      amount: !secret coin8_owned
      costs: !secret coin8_paid
    - market: !secret coin9_token
      amount: !secret coin9_owned
      costs: !secret coin9_paid
    - market: !secret coin10_token
      amount: !secret coin10_owned
      costs: !secret coin10_paid
    - market: !secret coin11_token
      amount: !secret coin11_owned
      costs: !secret coin11_paid

- platform: scrape
  name: !secret coin3_stake_title
  unit_of_measurement: !secret coin3_unit_of_measurement
  resource: !secret coin3_stakeinfo
  select: !secret coin3_scrape_selector
  value_template: '{{ float(value) / 1000000 }}'
  scan_interval: 3600

- platform: template
  sensors:
    crypto_portfolio_value:
      value_template: !secret crypto_portfolio_value
      friendly_name: "Portfolio value"
      icon_template: mdi:cash
      unit_of_measurement: '€'
    crypto_total_profit:
      value_template: !secret crypto_portfolio_profit
      friendly_name: "Profit total"
      icon_template: mdi:cash
      unit_of_measurement: '€'