- platform: bitvavo
  scan_interval: 5
  wallets:
    - market: !secret coin1_token
      amount: !secret coin1_owned
      costs: !secret coin1_paid
    - market: !secret coin2_token
      amount: !secret coin2_owned
      costs: !secret coin2_paid
    - market: !secret coin3_token
      amount: !secret coin3_owned
      costs: !secret coin3_paid
    - market: !secret coin4_token
      amount: !secret coin4_owned
      costs: !secret coin4_paid
