- alias: SA | Motion | Christmas Tree On
  trigger:
    - platform: state
      entity_id: binary_sensor.sa_motion_detected
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kitchen_motion_detected
      to: 'on'
  condition:
    condition: time
    after: '07:00:00'
    before: '03:00:00'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.0x000d6ffffedaf667_switch
          - switch.0x000d6ffffedc5e05_switch


- alias: SA | Motion | Christmas Tree Off
  trigger:
    platform: time_pattern
    minutes: '/10'
    seconds: 00
  condition:
    condition: and
    conditions:
      - platform: state
        entity_id: binary_sensor.sa_motion_detected
        state: 'off'
      - platform: state
        entity_id: binary_sensor.kitchen_motion_detected
        state: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.0x000d6ffffedaf667_switch
          - switch.0x000d6ffffedc5e05_switch
