- id: xmas_001
  alias: xmas_001
  trigger:
    - platform: state
      entity_id: binary_sensor.simulate_occupancy
      to: 'on'
    - platform: state
      entity_id: binary_sensor.simulate_occupancy
      to: 'off'
  action:
    service: scene.turn_on
    data_template:
      entity_id: >
        {% if trigger.to_state.state == 'on' %}
          scene.xmas_occupancy_sim
        {% elif trigger.to_state.state == 'off' %}
          scene.reset_xmas_occupancy_sim
        {% endif %}


- id: xmas_002
  alias: xmas_002
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.sa_motion_detected
        - binary_sensor.kitchen_motion_detected
      to: 'on'
  condition:
    condition: time
    after: '07:00:00'
    before: '03:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.christmas_lighting


- id: xmas_003
  alias: xmas_003
  trigger:
    platform: time_pattern
    minutes: '/10'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.sa_motion_detected
        state: 'off'
      - condition: state
        entity_id: binary_sensor.kitchen_motion_detected
        state: 'off'
  action:
    service: switch.turn_off
    entity_id:
      - switch.0x000d6ffffedaf667_switch
