- id: '1617977829904'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: Sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      time: '10:00:00'
      threshold: 15
      day: 1
      exclude:
        entity_id:
        - sensor.phone_person_one_battery_level
        - sensor.phone_person_two_battery_level
      actions:
      - service: notify.notify_matrix_clean
        data:
          message: Battery level(s) of {{sensors}} are extremely low!
- id: '1617978621558'
  alias: 'Motion Light | Office '
  description: ''
  use_blueprint:
    path: freakshock88/motion_illuminance_activated_entity.yaml
    input:
      motion_sensor: binary_sensor.0x00158d0004499f26_occupancy
      target_entity: script.scene_office_day
      illuminance_sensor: sensor.0x00158d0004499f26_illuminance
      illuminance_cutoff: input_number.office_illuminance_threshold
      blocker_entity: input_boolean.automation_office_light
      no_motion_wait: input_number.office_motion_timeout
- id: '1617981303816'
  alias: Window or door open | Stop Heating
  description: ''
  use_blueprint:
    path: xblackbytesx/window-open-climate-off.yaml
    input:
      window_entity: binary_sensor.lr_door_or_window_open
      climate_target: climate.living_room
      minimum_open_time: 90
- id: '1617983530934'
  alias: Window or door open | Stop Purifier
  description: ''
  use_blueprint:
    path: xblackbytesx/window-open-climate-off.yaml
    input:
      window_entity: binary_sensor.lr_door_or_window_open
      climate_target: fan.xiaomi_miio_device_2
      minimum_open_time: 90
- id: '1618048599345'
  alias: HW | Dynamic scene aware motion trigger
  description: ''
  use_blueprint:
    path: xblackbytesx/motion-light-dynamic-scene.yaml
    input:
      motion_entity: binary_sensor.hw_motion_detected
      target_entity: light.lg_hw_all
      target_entity_day_scene: script.scene_hw_day
      target_entity_night_scene: script.scene_hw_night
      sensor_dark_enough: binary_sensor.hw_dark_enough
      no_motion_timeout: input_number.hw_motion_timeout
      additional_off_entity: switch.0xec1bbdfffefd5a85
- id: '1618049197942'
  alias: CO | Dynamic scene aware motion trigger
  description: ''
  use_blueprint:
    path: xblackbytesx/motion-light-dynamic-scene.yaml
    input:
      motion_entity: binary_sensor.co_motion_detected
      target_entity: light.lg_co_all
      target_entity_day_scene: script.scene_co_day
      target_entity_night_scene: script.scene_co_night
      sensor_dark_enough: binary_sensor.co_dark_enough
      no_motion_timeout: input_number.co_motion_timeout
- id: '1618052131786'
  alias: Toilet | Dynamic scene aware motion trigger
  description: ''
  use_blueprint:
    path: xblackbytesx/motion-light-dynamic-scene.yaml
    input:
      motion_entity: binary_sensor.toilet_motion_detected
      target_entity: light.lg_toilet_all
      target_entity_day_scene: script.scene_toilet_day
      target_entity_night_scene: script.scene_toilet_night
      no_motion_timeout: input_number.toilet_motion_timeout
- id: '1618053623414'
  alias: Bathroom | Dynamic scene aware motion trigger
  description: ''
  use_blueprint:
    path: xblackbytesx/motion-light-dynamic-scene.yaml
    input:
      motion_entity: binary_sensor.bathroom_motion_detected
      target_entity: light.lg_bathroom_all
      target_entity_day_scene: script.scene_bathroom_day
      target_entity_night_scene: script.scene_bathroom_night
      sensor_dark_enough: binary_sensor.bathroom_dark_enough
      no_motion_timeout: input_number.bathroom_motion_timeout
- id: '1618053821325'
  alias: Kitchen | Dynamic scene aware motion trigger
  description: ''
  use_blueprint:
    path: xblackbytesx/motion-light-dynamic-scene.yaml
    input:
      motion_entity: binary_sensor.kitchen_motion_detected
      target_entity: light.lg_kitchen_all
      target_entity_day_scene: script.scene_kitchen_day
      target_entity_night_scene: script.scene_kitchen_night
      sensor_dark_enough: binary_sensor.kitchen_dark_enough
      no_motion_timeout: input_number.kitchen_motion_timeout
- id: '1618072747070'
  alias: Attic | Dynamic scene aware motion trigger
  description: ''
  use_blueprint:
    path: xblackbytesx/motion-light-dynamic-scene.yaml
    input:
      motion_entity: binary_sensor.attic_motion_detected
      target_entity: light.lg_attic_all
      target_entity_day_scene: script.scene_attic_day
      target_entity_night_scene: script.scene_attic_night
      sensor_dark_enough: binary_sensor.attic_dark_enough
      no_motion_timeout: input_number.attic_motion_timeout
- id: '1618076119249'
  alias: Office | Dynamic scene aware motion trigger
  description: ''
  use_blueprint:
    path: xblackbytesx/motion-light-dynamic-scene.yaml
    input:
      motion_entity: binary_sensor.office_motion_detected
      target_entity: light.lg_office_all
      target_entity_day_scene: script.scene_office_day
      target_entity_night_scene: script.scene_office_night
      sensor_dark_enough: binary_sensor.office_dark_enough
      no_motion_timeout: input_number.office_motion_timeout
- id: '1618130698559'
  alias: LB | Generic Ikea Remote Control
  description: ''
  use_blueprint:
    path: pavax/z2m-ikea-remote-controls.yaml
    input:
      remote: sensor.0x588e81fffe3ec5eb_click
      on_button_short:
      - service: script.turn_on
        target:
          entity_id: script.scene_lb_day
      off_button_short:
      - service: light.turn_off
        target:
          entity_id: light.lg_lb_all
      on_button_long:
      - service: script.turn_on
        target:
          entity_id: script.scene_lb_night
