- id: '1617977829904'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: Sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      time: '10:00:00'
      threshold: 15
      day: 1
      exclude:
        entity_id:
        - sensor.phone_person_one_battery_level
        - sensor.phone_person_two_battery_level
      actions:
      - service: notify.notify_matrix_clean
        data:
          message: Battery level(s) of {{sensors}} are extremely low!
- id: '1617981303816'
  alias: LR | Window or door open | Stop Heating
  description: ''
  use_blueprint:
    path: xblackbytesx/window-open-climate-off.yaml
    input:
      window_entity: binary_sensor.lr_door_or_window_open
      climate_target: climate.living_room
      minimum_open_time: 90
- id: '1617983530934'
  alias: LR | Window or door open | Stop Purifier
  description: ''
  use_blueprint:
    path: xblackbytesx/window-open-climate-off.yaml
    input:
      window_entity: binary_sensor.lr_door_or_window_open
      climate_target: fan.xiaomi_miio_device
      minimum_open_time: 90
- id: '1618048599345'
  alias: HW | Dynamic scene aware motion trigger
  description: ''
  use_blueprint:
    path: xblackbytesx/motion-light-dynamic-scene.yaml
    input:
      motion_entity: binary_sensor.hw_motion_detected
      target_entity: light.lg_hw_all
      target_entity_scene: script.scene_hw_smart
      sensor_dark_enough: binary_sensor.hw_dark_enough
      no_motion_timeout: input_number.hw_motion_timeout
      additional_off_entity: switch.0xec1bbdfffefd5a85
- id: '1618049197942'
  alias: CO | Dynamic scene aware motion trigger
  description: ''
  use_blueprint:
    path: xblackbytesx/motion-light-dynamic-scene.yaml
    input:
      motion_entity: binary_sensor.co_motion_detected
      target_entity: light.lg_co_all
      target_entity_scene: script.scene_co_smart
      sensor_dark_enough: binary_sensor.co_dark_enough
      no_motion_timeout: input_number.co_motion_timeout
- id: '1618052131786'
  alias: Toilet | Dynamic scene aware motion trigger
  description: ''
  use_blueprint:
    path: xblackbytesx/motion-light-dynamic-scene.yaml
    input:
      motion_entity: binary_sensor.toilet_motion_detected
      target_entity: light.lg_toilet_all
      target_entity_scene: script.scene_toilet_smart
      no_motion_timeout: input_number.toilet_motion_timeout
- id: '1618053623414'
  alias: Bathroom | Dynamic scene aware motion trigger
  description: ''
  use_blueprint:
    path: xblackbytesx/motion-light-dynamic-scene.yaml
    input:
      motion_entity: binary_sensor.bathroom_motion_detected
      target_entity: light.lg_bathroom_all
      target_entity_scene: script.scene_bathroom_smart
      sensor_dark_enough: binary_sensor.bathroom_dark_enough
      no_motion_timeout: input_number.bathroom_motion_timeout
- id: '1618053821325'
  alias: Kitchen | Dynamic scene aware motion trigger
  description: ''
  use_blueprint:
    path: xblackbytesx/motion-light-dynamic-scene.yaml
    input:
      motion_entity: binary_sensor.kitchen_motion_detected
      target_entity: light.lg_kitchen_all
      target_entity_scene: script.scene_kitchen_smart
      sensor_dark_enough: binary_sensor.kitchen_dark_enough
      no_motion_timeout: input_number.kitchen_motion_timeout
- id: '1618072747070'
  alias: Attic | Dynamic scene aware motion trigger
  description: ''
  use_blueprint:
    path: xblackbytesx/motion-light-dynamic-scene.yaml
    input:
      motion_entity: binary_sensor.attic_motion_detected
      target_entity: light.lg_attic_all
      target_entity_scene: script.scene_attic_smart
      sensor_dark_enough: binary_sensor.attic_dark_enough
      no_motion_timeout: input_number.attic_motion_timeout
- id: '1618076119249'
  alias: Office | Dynamic scene aware motion trigger
  description: ''
  use_blueprint:
    path: xblackbytesx/motion-light-dynamic-scene.yaml
    input:
      motion_entity: binary_sensor.office_motion_detected
      target_entity: light.lg_office_all
      target_entity_scene: script.scene_office_smart
      sensor_dark_enough: binary_sensor.office_dark_enough
      no_motion_timeout: input_number.office_motion_timeout
- id: '1618130698559'
  alias: LB | Generic Ikea Remote Control
  description: ''
  use_blueprint:
    path: pavax/z2m-ikea-remote-controls.yaml
    input:
      remote: sensor.0x588e81fffe3ec5eb_action
      on_button_short:
      - service: script.turn_on
        target:
          entity_id: script.scene_lb_smart
      off_button_short:
      - service: light.turn_off
        target:
          entity_id: light.lg_lb_all
      on_button_long:
      - service: script.turn_on
        target:
          entity_id: script.scene_lb_night
      off_button_long:
      - service: light.turn_off
        target:
          entity_id: light.lg_lb_all
- id: '1618253152030'
  alias: MB | Generic Ikea Remote Control
  description: ''
  use_blueprint:
    path: pavax/z2m-ikea-remote-controls.yaml
    input:
      remote: sensor.0x588e81fffe3567ee_action
      on_button_short:
      - service: script.turn_on
        target:
          entity_id: script.scene_mb_smart
      off_button_short:
      - service: light.turn_off
        target:
          entity_id: light.lg_mb_all
      on_button_long:
      - service: script.turn_on
        target:
          entity_id: script.scene_mb_smart
      off_button_long:
      - service: light.turn_off
        target:
          entity_id: light.lg_mb_all
- id: '1618253524498'
  alias: MB | Person1 | Generic Ikea Remote Control
  description: ''
  use_blueprint:
    path: pavax/z2m-ikea-remote-controls.yaml
    input:
      remote: sensor.0x680ae2fffeacab80_action
      on_button_short:
      - service: script.turn_on
        target:
          entity_id: script.scene_mb_smart
      off_button_short:
      - service: light.turn_off
        target:
          entity_id: light.lg_mb_all
- id: '1618253650053'
  alias: MB | Person 2 | Generic Ikea Remote Control
  description: ''
  use_blueprint:
    path: pavax/z2m-ikea-remote-controls.yaml
    input:
      remote: sensor.0x588e81fffe21f051_action
      on_button_short:
      - service: script.turn_on
        target:
          entity_id: script.scene_mb_smart
      off_button_short:
      - service: light.turn_off
        target:
          entity_id: light.lg_mb_all
- id: '1618299730580'
  alias: Office | Power Switch | Generic Ikea Remote Control
  description: ''
  use_blueprint:
    path: pavax/z2m-ikea-remote-controls.yaml
    input:
      on_button_short:
      - service: switch.turn_on
        target:
          entity_id: switch.power_office_desks
      remote: sensor.0x588e81fffe210c82_action
      off_button_short:
      - service: switch.turn_off
        target:
          entity_id: switch.power_office_desks
- id: '1618299962333'
  alias: Dryer | Power Switch | Generic Ikea Remote Control
  description: ''
  use_blueprint:
    path: pavax/z2m-ikea-remote-controls.yaml
    input:
      remote: sensor.0xec1bbdfffed45ff8_action
      on_button_short:
      - service: switch.turn_on
        target:
          entity_id: switch.power_attic_dryer
      off_button_short:
      - service: switch.turn_off
        target:
          entity_id: switch.power_attic_dryer
- id: '1618343026702'
  alias: SA | TV Switch | Generic Ikea Remote Control
  description: ''
  use_blueprint:
    path: pavax/z2m-ikea-remote-controls.yaml
    input:
      remote: sensor.0x680ae2fffe4d9610_action
      on_button_short:
      - service: switch.turn_on
        target:
          entity_id: switch.power_tv_cabinet
      off_button_short:
      - service: switch.turn_off
        target:
          entity_id: switch.power_tv_cabinet
- id: '1618343140289'
  alias: LR | Black Cabinet Switch | Generic Ikea Remote Control
  description: ''
  use_blueprint:
    path: pavax/z2m-ikea-remote-controls.yaml
    input:
      remote: sensor.0x588e81fffe0656b2_action
      on_button_short:
      - service: switch.turn_on
        target:
          entity_id: switch.power_black_cabinet
      off_button_short:
      - service: switch.turn_off
        target:
          entity_id: switch.power_black_cabinet
- id: '1618671825914'
  alias: SA | Smart Scene
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.sa_motion_detected
    to: 'on'
    from: 'off'
  - platform: state
    entity_id: binary_sensor.sa_tv_media_playing
    to: 'on'
    from: 'off'
  - platform: state
    entity_id: binary_sensor.sa_dark_enough
    to: 'on'
    from: 'off'
  - platform: state
    entity_id: binary_sensor.sa_motion_detected
    to: 'off'
    from: 'on'
    for: 00:05:00
  - platform: state
    entity_id: binary_sensor.sa_tv_media_playing
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: binary_sensor.sa_dark_enough
    from: 'on'
    to: 'off'
    for: 00:05:00
  condition: []
  action:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.sa_motion_detected
          state: 'off'
        - condition: state
          entity_id: binary_sensor.sa_dark_enough
          state: 'off'
      sequence:
      - service: light.turn_off
        target:
          entity_id: light.lg_sa_all
    default:
    - service: script.turn_on
      target:
        entity_id: script.scene_lr_smart
  mode: restart
- id: '1618689298301'
  alias: EX | Lights
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.allow_exterior_lights
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.allow_exterior_lights
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: binary_sensor.exterior_dark_enough
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.exterior_dark_enough
    from: 'on'
    to: 'off'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.allow_exterior_lights
          state: 'off'
        - condition: state
          entity_id: binary_sensor.exterior_dark_enough
          state: 'off'
      sequence:
      - service: light.turn_off
        target:
          entity_id: light.lg_ex_all
      - service: switch.turn_off
        target:
          entity_id: switch.power_exterior
    default:
    - service: script.turn_on
      target:
        entity_id: script.scene_ex_smart
  mode: single
- id: '1618832529405'
  alias: LB | Fan | Generic Ikea Remote Control
  description: ''
  use_blueprint:
    path: pavax/z2m-ikea-remote-controls.yaml
    input:
      remote: sensor.0x680ae2fffe4b23fd_action
      on_button_short:
      - type: turn_on
        device_id: 2f5a54dfc2cf4ffe85023b7f0fb89ef8
        entity_id: switch.0x086bd7fffe5185b6_switch
        domain: switch
      off_button_short:
      - type: turn_off
        device_id: 2f5a54dfc2cf4ffe85023b7f0fb89ef8
        entity_id: switch.0x086bd7fffe5185b6_switch
        domain: switch
- id: '1618832780984'
  alias: SB | Fan | Generic Ikea Remote Control
  description: ''
  use_blueprint:
    path: pavax/z2m-ikea-remote-controls.yaml
    input:
      remote: sensor.0x680ae2fffeaa1661_action
      on_button_short:
      - type: turn_on
        device_id: 97b88140e062437ba546e3b5936bf4bd
        entity_id: switch.0x000b3cfffef7b582_switch
        domain: switch
      off_button_short:
      - type: turn_off
        device_id: 97b88140e062437ba546e3b5936bf4bd
        entity_id: switch.0x000b3cfffef7b582_switch
        domain: switch
- id: '1618849119911'
  alias: LB | Auto light off
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.lb_motion_detected
    to: 'on'
    from: 'off'
  - platform: state
    entity_id: binary_sensor.lb_motion_detected
    from: 'on'
    to: 'off'
    for: 00:10:00
  - platform: state
    entity_id: binary_sensor.lb_dark_enough
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.lb_dark_enough
    from: 'on'
    to: 'off'
    for: 00:05:00
  condition: []
  action:
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: binary_sensor.lb_dark_enough
          state: 'on'
        - condition: state
          entity_id: binary_sensor.lb_motion_detected
          state: 'on'
      sequence:
      - service: script.turn_on
        target:
          entity_id: script.scene_lb_smart
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: binary_sensor.lb_motion_detected
          state: 'off'
        - condition: state
          entity_id: binary_sensor.allow_turning_off_bedroom_lights
          state: 'on'
      - condition: and
        conditions:
        - condition: state
          entity_id: binary_sensor.lb_dark_enough
          state: 'off'
        - condition: state
          entity_id: binary_sensor.allow_turning_off_bedroom_lights
          state: 'on'
      sequence:
      - service: light.turn_off
        target:
          entity_id: light.lg_lb_all
    default: []
  mode: single
