- platform: workday
  name: Working person one
  country: NL
  workdays: !secret person_one_workdays

- platform: workday
  name: Working person two
  country: NL
  workdays: !secret person_two_workdays

- platform: template
  sensors:
    catflap_activity:
      value_template: >-
        {{ is_state('sensor.0x00158d000313127e_action', 'tilt')
           or is_state('sensor.0x00158d000313127e_action', 'drop') }}
