- platform: workday
  name: Working person one
  country: NL
  workdays: !secret person_one_workdays

- platform: workday
  name: Working person two
  country: NL
  workdays: !secret person_two_workdays

- platform: tod
  name: Early Morning
  after: '07:00'
  before: '09:59'

- platform: tod
  name: Late Morning
  after: '10:00'
  before: '11:59'

- platform: tod
  name: Early Afternoon
  after: '12:00'
  before: '14:59'

- platform: tod
  name: Late Afternoon
  after: '15:00'
  before: '17:59'

- platform: tod
  name: Early Evening
  after: '18:00'
  before: '19:59'

- platform: tod
  name: Late Evening
  after: '20:00'
  before: '22:29'

- platform: tod
  name: Early Night
  after: '22:30'
  before: '02:59'

- platform: tod
  name: Late Night
  after: '03:00'
  before: '06:59'

- platform: template
  sensors:
    time_for_dim_scenes:
      value_template: >-
        {{ is_state('binary_sensor.early_night', 'on')
           or is_state('binary_sensor.late_night', 'on') }}

- platform: template
  sensors:
    sa_allow_media_status_scene_switching:
      value_template: >-
        {{ is_state('binary_sensor.late_evening', 'on')
           or is_state('binary_sensor.early_night', 'on')
           or is_state('binary_sensor.late_night', 'on') }}

- platform: template
  sensors:
    allow_exterior_lights:
      value_template: >-
        {{ is_state('binary_sensor.late_afternoon', 'on')
          or is_state('binary_sensor.early_evening', 'on')
          or is_state('binary_sensor.late_evening', 'on')
          or is_state('binary_sensor.early_night', 'on') }}