- platform: rfxtrx
  automatic_add: False
  devices:
    0b11000001a1dbda0a010f70:
      name: motion_sensor_sa
      device_class: motion

    0b11000201a1dc7e0a010f70:
      name: motion_sensor_attic
      device_class: motion

    0b1100000128efc60a000070:
      name: front_door
      device_class: window

- platform: workday
  name: !secret working_person_one
  country: NL
  workdays: !secret workdays_person_one

- platform: workday
  name: !secret working_person_two
  country: NL
  workdays: !secret workdays_person_two
