- platform: workday
  name: Working person one
  country: NL
  workdays: !secret person_one_workdays

- platform: workday
  name: Working person two
  country: NL
  workdays: !secret person_two_workdays

- platform: template
  sensors:
    sa_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.hue_motion_sensor_sitting_area_motion', 'on')
           or is_state('binary_sensor.0x00158d00034911fc_occupancy', 'on')
           or is_state('binary_sensor.motion_sensor_sa', 'on') }}

    sa_dark_enough:
      value_template: >-
        {{ states('sensor.hue_motion_sensor_sitting_area_light_level')|float < 18 }}

    kitchen_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.hue_motion_sensor_kitchen_motion', 'on')
           or is_state('binary_sensor.0x00158d00033a43ef_occupancy', 'on') }}

    kitchen_dark_enough:
      value_template: >-
        {{ states('sensor.hue_motion_sensor_kitchen_light_level')|float < 25 }}

    hw_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.hue_motion_sensor_hallway_door_motion', 'on')
           or is_state('binary_sensor.0x00178801020282bc_occupancy', 'on') }}

    hw_dark_enough:
      value_template: >-
        {{ states('sensor.0x00178801020282bc_illuminance')|float < 3000 }}

    co_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.hue_motion_sensor_corridor_motion', 'on') }}

    co_dark_enough:
      value_template: >-
        {{ states('sensor.hue_motion_sensor_corridor_light_level')|float < 18 }}

    bathroom_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x00158d000349234a_occupancy', 'on')
           or is_state('binary_sensor.0x00158d00033aac53_occupancy', 'on') }}

    bathroom_dark_enough:
      value_template: >-
        {{ states('sensor.0x00158d000349234a_illuminance')|float < 100 }}

    attic_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x00158d00036b62d0_occupancy', 'on')
           or is_state('binary_sensor.0x00158d000302ec77_occupancy', 'on') }}

    attic_dark_enough:
      value_template: >-
        {{ states('sensor.0x00158d00036b62d0_illuminance')|float < 100 }}

    exterior_dark_enough:
      value_template: >-
        {{ states('sensor.hue_motion_sensor_sitting_area_light_level')|float < 18 }}
