- platform: rfxtrx
  automatic_add: False
  devices:
    0b11000001a1dbda0a010f70:
      name: motion_sensor_sa
      device_class: motion

    0b11000201a1dc7e0a010f70:
      name: motion_sensor_attic
      device_class: motion

    0b1100000128efc60a000070:
      name: front_door
      device_class: window

- platform: workday
  name: Working person one
  country: NL
  workdays: !secret person_one_workdays

- platform: workday
  name: Working person two
  country: NL
  workdays: !secret person_two_workdays

- platform: template
  sensors:
    sa_tv_media_playing:
      value_template: >-
        {{ is_state('media_player.living_room', 'playing')
           or is_state('media_player.kodi', 'playing')
           or is_state('input_boolean.sa_media_status_override', 'on') }}

    sa_motion_detected:
      value_template: >-
        {{ is_state('sensor.motion_in_sitting_area', '1')
           or is_state('binary_sensor.motion_sensor_sa', 'on') }}

    sa_dark_enough:
      value_template: >-
          {{ sensor.illumination_in_sitting_area|float < 18 }}

    kitchen_motion_detected:
      value_template: >-
        {{ is_state('sensor.motion_in_kitchen', '1') }}

    kitchen_dark_enough:
      value_template: >-
          {{ sensor.illumination_in_kitchen|float < 25 }}

    hw_motion_detected:
      value_template: >-
        {{ is_state('sensor.motion_in_hallway_door', '1')
           or is_state('sensor.motion_in_hallway_stairs', '1') }}

    hw_dark_enough:
      value_template: >-
          {{ sensor.illumination_in_hallway_stairs|float < 18 }}

    co_motion_detected:
      value_template: >-
        {{ is_state('sensor.motion_in_corridor', '1') }}

    co_dark_enough:
      value_template: >-
          {{ sensor.illumination_in_corridor|float < 18 }}
