- platform: rfxtrx
  automatic_add: False
  devices:
    0b11000001a1dbda0a010f70:
      name: motion_sensor_sa
      device_class: motion

    0b11000201a1dc7e0a010f70:
      name: motion_sensor_attic
      device_class: motion

    0b1100000128efc60a000070:
      name: front_door
      device_class: window

- platform: workday
  name: Working person one
  country: NL
  workdays: !secret person_one_workdays

- platform: workday
  name: Working person two
  country: NL
  workdays: !secret person_two_workdays

- platform: template
  sensors:
    sa_tv_media_playing:
      value_template: >-
        {{ is_state('media_player.living_room', 'playing')
           or is_state('media_player.kodi', 'playing')
           or is_state('media_player.playstation_4', 'playing')
           or is_state('input_boolean.sa_media_status_override', 'on') }}

    sa_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.hue_motion_sensor_sitting_area_motion', 'on')
           or is_state('binary_sensor.motion_sensor_sa', 'on') }}

    sa_dark_enough:
      value_template: >-
        {{ states('sensor.hue_motion_sensor_sitting_area_light_level')|float < 18 }}

    kitchen_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.hue_motion_sensor_kitchen_motion', 'on') }}

    kitchen_dark_enough:
      value_template: >-
        {{ states('sensor.hue_motion_sensor_kitchen_light_level')|float < 25 }}

    hw_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.hue_motion_sensor_hallway_door_motion', 'on')
           or is_state('binary_sensor.hue_motion_sensor_hallway_stairs_motion', 'on') }}

    hw_dark_enough:
      value_template: >-
        {{ states('sensor.hue_motion_sensor_hallway_stairs_light_level')|float < 18 }}

    co_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.hue_motion_sensor_corridor_motion', 'on') }}

    co_dark_enough:
      value_template: >-
        {{ states('sensor.hue_motion_sensor_corridor_light_level')|float < 18 }}

    attic_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.motion_sensor_attic', 'on') }}

    exterior_dark_enough:
      value_template: >-
        {{ states('sensor.hue_motion_sensor_sitting_area_light_level')|float < 18 }}
