- platform: foscam
  ip: 10.0.221.32
  username: !secret foscam1_username
  password: !secret foscam1_password

- platform: ffmpeg
  name: XiaoFang1
  input: -rtsp_transport tcp -i rtsp://10.0.221.34/unicast
  extra_arguments: -pred 1
