homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret ha_http_api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

light:
  platform: hue
  host: 10.0.221.30

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

mqtt:
  broker: !secret mqtt_broker_url
  port: !secret mqtt_broker_port
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_broker_username
  password: !secret mqtt_broker_password

device_tracker:
  - platform: owntracks

zone:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  radius: 100
  icon: mdi:home

zone 2:
  name: Work
  latitude: !secret zone_work_latitude
  longitude: !secret zone_work_longitude
  radius: 100

# Text to speech
tts:
  platform: google

automation: !include_dir_merge_list automation/
sensor: !include_dir_merge_list sensor/
notify: !include_dir_merge_list notify/
media_player: !include_dir_merge_list media_players/
camera: !include_dir_merge_list camera/
group: !include_dir_merge_named layout/
scene: !include_dir_merge_list scene/
