homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret ha_http_api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Rfxtrx
rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A11D2A5T-if00-port0

switch:
  platform: rfxtrx
  automatic_add: false
  devices:
    # freq1but1
    0b110000019c0be201000070:
      name: programmable_one
    # freq1but2
    0b110002019c0be202010f70:
      name: programmable_two
    # freq1but3
    0b110000019c0be203010f70:
      name: programmable_three
    # freq1but4
    0b110003019c0be204010f70:
      name: programmable_four

    # freq2but1
    0b11001e019c0be205010f70:
      name: programmable_five
    # freq2but2
    0b110020019c0be206010f70:
      name: programmable_six
    # freq2but3
    0b110021019c0be207010f70:
      name: programmable_seven
    # freq2but4
    0b110022019c0be208010f70:
      name: programmable_eight

    # freq3but1
    0b110024019c0be209010f70:
      name: power_socket_one
    # freq3but2
    0b110025019c0be20a010f70:
      name: power_socket_two
    # freq3but3
    0b110026019c0be20b010f60:
      name: power_socket_three
    # # freq3but4
    # 0b110027019c0be20c010f70:
    #   name: power_socket_four

    0710010048050160:
      name: beamer_screen
    0710010448060160:
      name: sun_screen

binary_sensor:
  platform: rfxtrx
  devices:
    0b11000001a1dbda0a010f70:
      name: motion_sensor_sa
      device_class: motion

hue:
  bridges:
    - host: 10.0.221.30

light:
  - platform: flux_led
    devices:
      10.0.221.31:
        name: Ledstrip TV Cabinet
        protocol: 'ledenet'
        mode: "rgbw"

  - platform: rfxtrx
    devices:
      # freq4but1
      0b110028019c0be20d010f60:
        name: dimmable_socket_one
      # freq4but2
      0b110029019c0be20e010f70:
        name: dimmable_socket_two
      # # freq4but3
      # 0b11002a019c0be20f010f70:
      #   name: dimmable_socket_three
      # # freq4but4
      # 0b11002b019c0be210010f70:
      #   name: dimmable_socket_four

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

mqtt:
  broker: !secret mqtt_broker_url
  port: !secret mqtt_broker_port
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_broker_username
  password: !secret mqtt_broker_password

device_tracker:
  - platform: owntracks

zone:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  radius: 100
  icon: mdi:home

zone 2:
  name: Work
  latitude: !secret zone_work_latitude
  longitude: !secret zone_work_longitude
  radius: 100

# Text to speech
tts:
  platform: google

automation: !include_dir_merge_list automation/
sensor: !include_dir_merge_list sensor/
input_boolean: !include_dir_merge_named boolean/
notify: !include_dir_merge_list notify/
media_player: !include_dir_merge_list media_players/
camera: !include_dir_merge_list camera/
group: !include_dir_merge_named layout/
script: !include_dir_merge_named script/
#scene: !include_dir_merge_list scene/
