homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  # packages:
  #   pack_1: !include packages/christmas_package.yaml

hassio:
config:
# discovery:
history:
logbook:
map:
sun:
# cloud:

frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest

lovelace:
  mode: yaml

http:
  # api_password: !secret http_password
  ssl_certificate: /config/certificate.pem
  ssl_key: /config/privkey.pem
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  # use_x_forwarded_for: True
  # trusted_proxies:
  #   - 127.0.0.1
  #   - ::1
  # trusted_networks:
  #   - 127.0.0.1
  #   - ::1
  #   - 10.0.0.0/24
  #   - fd00::/8

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

custom_updater:
  track:
    - cards
    - components

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
  intents:
    LivingRoomTemperature:
     - What is the temperature in the living room

intent_script:
  LivingRoomTemperature:
    speech:
      text: It is currently {{ states.sensor.living_room_thermostat_temperature }} degrees in the living room.

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key

tts:
  - platform: google

hue:
  bridges:
    - host: 10.0.221.30
      filename: philips-hue.conf

# Rfxtrx
rfxtrx:
  device: /dev/ttyUSB0

cast:
  chromecast:
  - host: 10.0.221.26
  chromecast_audio:
  - host: 10.0.221.29

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# plant: !include plants.yaml
switch: !include switch.yaml
cover: !include cover.yaml
binary_sensor: !include binary_sensor.yaml
light: !include light.yaml
matrix: !include matrix.yaml
# notify: !include_dir_merge_list notify/
# automation: !include_dir_merge_list automation/
sensor: !include_dir_merge_list sensor/
input_boolean: !include_dir_merge_named boolean/
media_player: !include_dir_merge_list media_player/
device_tracker: !include_dir_merge_list device_tracker/
# camera: !include_dir_merge_list camera/
script: !include_dir_merge_named script/
# group: !include_dir_merge_named layout/

shell_command:
  lovelace_gen: 'python /config/lovelace-gen.py'
