# default_config:
# Stripped out what I don't use
# automation:
# cloud:
config:
# counter:
# discovery
frontend:
history:
# image:
# input_boolean:
# input_datetime:
# input_number:
# input_select:
# input_text:
logbook:
# map:
# media_source:
mobile_app:
# person:
# scene:
# script:
# ssdp:
# sun:
system_health:
tag:
# timer:
updater:
# zeroconf:
zone:

# Additional config:
http:
  cors_allowed_origins:
    - !secret base_url
    - https://google.com
    - https://www.home-assistant.io

panel_iframe:
  router:
    title: "Zigbee"
    icon: "zigbee"
    url: !secret zigbee_dashboard_url
    require_admin: true

lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml

python_script:

recorder:
  db_url: !secret database_connection_string
  purge_keep_days: 4

wake_on_lan:

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam

  packages:
    global_package: !include packages/pkg_global/all.yaml
    zigbee2mqtt_package: !include packages/pkg_zigbee2mqtt/all.yaml
    rfx_package: !include packages/pkg_rfx/all.yaml
    light_package: !include packages/pkg_light/all.yaml
    matrix_package: !include packages/pkg_matrix/all.yaml
    presence_package: !include packages/pkg_presence/all.yaml
    transportation_package: !include packages/pkg_transportation/all.yaml
    climate_package: !include packages/pkg_climate/all.yaml
    solar_package: !include packages/pkg_solar/all.yaml
    media_package: !include packages/pkg_media/all.yaml
    network_package: !include packages/pkg_network/all.yaml
    smoke_package: !include packages/pkg_smoke/all.yaml
    plants_package: !include packages/pkg_plants/all.yaml
    finance_package: !include packages/pkg_finance/all.yaml
    security_package: !include packages/pkg_security/all.yaml
    astronomy_package: !include packages/pkg_astronomy/all.yaml
    shell_commands_package: !include packages/pkg_shell_commands/all.yaml
    speech_package: !include packages/pkg_speech/all.yaml
    # christmas_package: !include packages/pkg_christmas/all.yaml
    coronavirus_package: !include packages/pkg_coronavirus/all.yaml