homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret ha_http_api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# sensor: !include_dir_list sensor

notify:
  - name: Pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

light:
  platform: hue
  host: 10.0.221.30

nest:
  client_id: !secret nest_client_id 
  client_secret: !secret nest_client_secret 

media_player: !include media_players.yaml

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

camera: !include cameras.yaml

# mqtt: !include mqtt/hass.yaml

# Text to speech
tts:
  platform: google

group: !include groups.yaml
