homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

# Enables Hass.io
hassio:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

hue:
  bridges:
    - host: 10.0.221.30
      filename: philips-hue.conf

# Rfxtrx
rfxtrx:
  device: /dev/ttyUSB0

switch: !include switch.yaml
cover: !include cover.yaml
binary_sensor: !include binary_sensor.yaml
light: !include light.yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

matrix: !include matrix.yaml

notify: !include_dir_merge_list notify/
automation: !include_dir_merge_list automation/
sensor: !include_dir_merge_list sensor/
input_boolean: !include_dir_merge_named boolean/
media_player: !include_dir_merge_list media_player/
camera: !include_dir_merge_list camera/
script: !include_dir_merge_named script/
group: !include_dir_merge_named layout/
