homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

  packages:
    zigbee2mqtt_package: !include packages/pkg_zigbee2mqtt/all.yaml
    rfx_package: !include packages/pkg_rfx/all.yaml
    matrix_package: !include packages/pkg_matrix/all.yaml
    presence_package: !include packages/pkg_presence/all.yaml
    climate_package: !include packages/pkg_climate/all.yaml
    media_players_package: !include packages/pkg_media_players/all.yaml
    camera_package: !include packages/pkg_camera/all.yaml
    smoke_package: !include packages/pkg_smoke/all.yaml
    plants_package: !include packages/pkg_plants/all.yaml
    finance_package: !include packages/pkg_finance/all.yaml
    shell_commands_package: !include packages/pkg_shell_commands/all.yaml
    speech_package: !include packages/pkg_speech/all.yaml
    # christmas_package: !include packages/pkg_christmas/all.yaml

hassio:
config:
history:
# logbook:
system_health:
wake_on_lan:
# map:
sun:
# cloud:

recorder:
 purge_keep_days: 4

# discovery:
#   ignore:
#     - yeelight

frontend:
  themes: !include themes.yaml
  javascript_version: latest

lovelace:
  mode: yaml

http:
  ssl_certificate: /config/certificate.pem
  ssl_key: /config/privkey.pem
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  # use_x_forwarded_for: True
  # trusted_proxies:
  #   - 127.0.0.1
  #   - ::1
  # trusted_networks:
  #   - 127.0.0.1
  #   - ::1
  #   - 10.0.0.0/24
  #   - fd00::/8

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  
hue:
  bridges:
    - host: 10.0.221.30
      filename: philips-hue.conf

yeelight:
  devices:
    10.0.221.37:
      name: Ledstrip Black Cabinet
      transition: 1000
    10.0.221.39:
      name: Ledstrip Kitchen Cabinet
      transition: 1000
    10.0.221.38:
      name: Ledstrip Large Bedroom
      transition: 1000

transmission:
  host: !secret synology_ip
  username: !secret transmission_user
  password: !secret transmission_pass
  monitored_conditions:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
    - 'active_torrents'
    - 'paused_torrents'
    - 'started_torrents'
    - 'completed_torrents'
    - 'total_torrents'

speedtestdotnet:
  scan_interval:
    hours: 6
  monitored_conditions:
    - ping
    - download
    - upload

alert: !include alerts.yaml
binary_sensor: !include binary_sensor.yaml
light: !include light.yaml
automation: !include_dir_merge_list automation/
sensor: !include_dir_merge_list sensor/
input_boolean: !include_dir_merge_named boolean/
scene: !include_dir_merge_list scene/
