- platform: flux_led
  devices:
    10.0.221.31:
      name: Ledstrip TV Cabinet
      protocol: 'ledenet'
      mode: "rgbw"

- platform: group
  name: LG | SA | LED strips
  entities:
    - light.ledstrip_tv_cabinet
    - light.ledstrip_black_cabinet

- platform: group
  name: LG | LR | LED strips
  entities:
    - light.lg__sa__led_strips
    - light.ledstrip_kitchen_cabinet

- platform: group
  name: LG | SA | All
  entities:
    - light.hue_bulb_standing_lamp
    - light.hue_go_closet_l
    - light.hue_go_closet_r
    - light.hue_iris_tv_cabinet
    - light.hue_candle_salt_lamp

- platform: group
  name: LG | Kitchen | All
  entities:
    - light.hue_bulb_kitchen_table_l
    - light.hue_bulb_kitchen_table_r
    - light.hue_spot_kitchen_counter_1
    - light.hue_spot_kitchen_counter_2
    - light.hue_spot_kitchen_counter_3
    - light.hue_spot_kitchen_counter_4

- platform: group
  name: LG | LR | All
  entities:
    - light.lg__sa__all
    - light.lg__kitchen__all
    - light.lg__lr__led_strips

- platform: group
  name: LG | EX | All
  entities:
    - light.0x00158d00017934ff_light
    - light.0x00158d00017ab8da_light

- platform: group
  name: LG | MB | All
  entities:
    - light.0x00158d00017cd686_light

- platform: group
  name: LG | SB | All
  entities:
    - light.0x90fd9ffffeea4e5e_light

- platform: group
  name: LG | Attic | All
  entities:
    - light.0x00158d0001793961_light
    # - light.0x00158d0000dcb62a_light
