- platform: flux_led
  devices:
    10.0.221.31:
      name: Ledstrip TV Cabinet
      protocol: 'ledenet'
      mode: "rgbw"

- platform: group
  name: Living room LED strips
  entities:
    - light.ledstrip_tv_cabinet
    - light.ledstrip_black_cabinet
    - light.ledstrip_kitchen_cabinet

- platform: group
  name: Sitting Area LED strips
  entities:
    - light.ledstrip_tv_cabinet
    - light.ledstrip_black_cabinet

- platform: group
  name: Exterior lighting
  entities:
    - light.0x00158d00017934ff_light
    - light.0x00158d00017ab8da_light

- platform: group
  name: Master bedroom
  entities:
    - light.0x00158d00017cd686_light

- platform: group
  name: Small bedroom
  entities:
    - light.0x90fd9ffffeea4e5e_light

- platform: group
  name: Attic
  entities:
    - light.0x00158d0001793961_light
    # - light.0x00158d0000dcb62a_light
