- platform: flux_led
  devices:
    10.0.221.31:
      name: Ledstrip TV Cabinet
      protocol: 'ledenet'
      mode: "rgbw"

- platform: group
  name: LG | HW | All
  entities:
    - light.0x0017880103ea3a60_light

- platform: group
  name: LG | SA | LED strips
  entities:
    - light.ledstrip_tv_cabinet
    - light.ledstrip_black_cabinet

- platform: group
  name: LG | LR | LED strips
  entities:
    - light.lg_sa_led_strips
    - light.ledstrip_kitchen_cabinet

- platform: group
  name: LG | SA | All
  entities:
    - light.hue_bulb_standing_lamp
    - light.hue_go_closet_l
    - light.hue_go_closet_r
    - light.hue_iris_tv_cabinet
    - light.hue_candle_salt_lamp
    - light.lg_sa_led_strips

- platform: group
  name: LG | Kitchen | Table
  entities:
    - light.hue_bulb_kitchen_table_l
    - light.hue_bulb_kitchen_table_r

- platform: group
  name: LG | Kitchen | Counter
  entities:
    - light.hue_spot_kitchen_counter_1
    - light.hue_spot_kitchen_counter_2
    - light.hue_spot_kitchen_counter_3
    - light.hue_spot_kitchen_counter_4

- platform: group
  name: LG | Kitchen | All
  entities:
    - light.lg_kitchen_table
    - light.lg_kitchen_counter
    - light.ledstrip_kitchen_cabinet

- platform: group
  name: LG | LR | All
  entities:
    - light.lg_sa_all
    - light.lg_kitchen_all

- platform: group
  name: LG | EX | All
  entities:
    - light.0x00158d00017934ff_light
    - light.0x00158d00017ab8da_light

- platform: group
  name: LG | MB | All
  entities:
    - light.0x00158d00017cd686_light

- platform: group
  name: LG | SB | All
  entities:
    - light.0x90fd9ffffeea4e5e_light
    - light.dimmable_socket_one

- platform: group
  name: LG | LB | All
  entities:
    - light.0x00178801039d140f_light
    - light.ledstrip_large_bedroom

- platform: group
  name: LG | CO | All
  entities:
    - light.0x00178801030a3dde_light

- platform: group
  name: LG | Bathroom | All
  entities:
    - light.hue_candle_bathroom_l
    - light.hue_bulb_bathroom_r

- platform: group
  name: LG | Attic | All
  entities:
    - light.0x00158d0001793961_light
    - light.0x00158d0000dcb62a_light
