# - platform: yr

- platform: darksky
  api_key: !secret dark_sky_api_key
  monitored_conditions:
    - summary
    - icon
    - temperature
    - apparent_temperature
    - wind_speed

- platform: rest
  resource: !secret hallway_stairs_lux_url
  # value_template: '{{ value_json.state.lightlevel }}'
  value_template: '{{ (10 ** (float(value_json.state.lightlevel - 1) / 10000))|round(1) }}'
  unit_of_measurement: Lux
  name: 'Illumination in hallway/stairs'

- platform: rest
  resource: !secret sitting_area_lux_url
  # value_template: '{{ value_json.state.lightlevel }}'
  value_template: '{{ (10 ** (float(value_json.state.lightlevel - 1) / 10000))|round(1) }}'
  unit_of_measurement: Lux
  name: 'Illumination in sitting area'

- platform: rest
  resource: !secret hallway_door_lux_url
  # value_template: '{{ value_json.state.lightlevel }}'
  value_template: '{{ (10 ** (float(value_json.state.lightlevel - 1) / 10000))|round(1) }}'
  unit_of_measurement: Lux
  name: 'Illumination in hallway/door'

- platform: rest
  resource: !secret hallway_stairs_temp_url
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Temperature in hallway/stairs'

- platform: rest
  resource: !secret sitting_area_temp_url
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Temperature in sitting area'

- platform: rest
  resource: !secret hallway_door_temp_url
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Temperature in hallway/door'

- platform: rest
  resource: !secret hallway_stairs_motion_url
  value_template: '{{ value_json.state.status }}'
  scan_interval: 2
  name: 'Motion in hallway/stairs'

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
