# lovelace_gen

title: Bier Estates
resources:
- url: !file /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js
  type: js
- url: !file /local/custom-lovelace/lovelace-auto-entities/auto-entities.js
  type: module
- url: !file /local/custom-lovelace/lovelace-swipe-navigation/swipe-navigation.js
  type: js
- url: !file /local/custom-lovelace/lovelace-bar-card/bar-card.js
  type: js
- url: !file /local/custom-lovelace/lovelace-card-tools/card-tools.js
  type: js
- url: !file /local/custom-lovelace/lovelace-fold-entity-row/fold-entity-row.js
  type: js
- url: !file /local/custom-lovelace/lovelace-mini-graph-card/mini-graph-card-bundle.js
  type: js
- url: !file /local/custom-lovelace/lovelace-mini-media-player/mini-media-player-bundle.js
  type: js
- url: !file /local/custom-lovelace/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js
  type: module

!include lovelace/macros.yaml

views:
  - !include lovelace/home.yaml
  - !include lovelace/ground_floor.yaml
  - !include lovelace/first_floor.yaml
  - !include lovelace/attic.yaml
  - !include lovelace/exterior.yaml
  - !include lovelace/people.yaml
  - !include lovelace/plants.yaml
  - !include lovelace/media.yaml
  - !include lovelace/scenes.yaml
  - !include lovelace/security.yaml
  - !include lovelace/network.yaml
  - !include lovelace/finance.yaml
  - !include lovelace/automation.yaml
  - !include lovelace/overrides.yaml
