# lovelace_gen

title: Bier Estates

custom_header:
  # compact_mode: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)

decluttering_templates:
  scene_tile:
    type: vertical-stack
    cards:
      - type: markdown
        content: >
          ## '[[title]]'
      - type: glance
        show_name: false
        show_state: false
        entities:
          - entity: '[[entity_1]]'
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: '[[entity_1]]'
      - type: glance
        show_name: false
        show_state: false
        entities:
          - entity: '[[entity_2]]'
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: '[[entity_2]]'
      - type: glance
        show_name: false
        show_state: false
        entities:
          - entity: '[[entity_3]]'
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: '[[entity_3]]'
      - type: glance
        show_name: false
        show_state: false
        entities:
          - entity: '[[entity_4]]'
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: '[[entity_4]]'

resources:
- url: !file /local/custom-lovelace/decluttering-card/decluttering-card.js
  type: module
- url: !file /local/custom-lovelace/custom-header/custom-header.js
  type: module
- url: !file /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js
  type: js
- url: !file /local/custom-lovelace/lovelace-auto-entities/auto-entities.js
  type: module
- url: !file /local/custom-lovelace/lovelace-swipe-navigation/swipe-navigation.js
  type: js
- url: !file /local/custom-lovelace/button-card/button-card.js
  type: module
- url: !file /local/custom-lovelace/lovelace-bar-card/bar-card.js
  type: js
- url: !file /local/custom-lovelace/lovelace-card-tools/card-tools.js
  type: js
- url: !file /local/custom-lovelace/lovelace-fold-entity-row/fold-entity-row.js
  type: js
- url: !file /local/custom-lovelace/lovelace-mini-graph-card/mini-graph-card-bundle.js
  type: js
- url: !file /local/custom-lovelace/lovelace-mini-media-player/mini-media-player-bundle.js
  type: js
- url: !file /local/custom-lovelace/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js
  type: module

views:
  - !include lovelace/home.yaml
  - !include lovelace/ground_floor.yaml
  - !include lovelace/first_floor.yaml
  - !include lovelace/attic.yaml
  - !include lovelace/exterior.yaml
  - !include lovelace/people.yaml
  - !include lovelace/plants.yaml
  - !include lovelace/media.yaml
  - !include lovelace/scenes.yaml
  - !include lovelace/security.yaml
  - !include lovelace/network.yaml
  - !include lovelace/finance.yaml
  - !include lovelace/battery.yaml
  - !include lovelace/automation.yaml
  - !include lovelace/overrides.yaml
