title: Bier Estates

decluttering_templates: !include_dir_merge_named lovelace/decluttering_templates/

views:
  - !include lovelace/home.yaml
  - !include lovelace/ground_floor.yaml
  - !include lovelace/first_floor.yaml
  - !include lovelace/attic.yaml
  - !include lovelace/exterior.yaml
  - !include lovelace/people.yaml
  - !include lovelace/plants.yaml
  - !include lovelace/media.yaml
  - !include lovelace/scenes.yaml
  - !include lovelace/security.yaml
  - !include lovelace/network.yaml
  - !include lovelace/finance.yaml
  - !include lovelace/disease.yaml
  - !include lovelace/battery.yaml
  - !include lovelace/automation.yaml
  - !include lovelace/overrides.yaml
