- alias: Attic | Motion | Lights on
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_attic
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.kitchen_meets_darkness_cutoff
        state: 'on'
      - condition: time
        after: '06:00:00'
        before: '02:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.attic
        brightness_pct: 70
        kelvin: 2700
