- alias: Attic | Motion | Lights off
  trigger:
    - platform: state
      entity_id: binary_sensor.attic_motion_detected
      to: 'off'
      for:
        minutes: 3
    - platform: state
      entity_id: binary_sensor.attic_dark_enough
      to: 'off'
      for:
        minutes: 5
  action:
    - service: light.turn_off
      entity_id: light.lg_attic_all
