- alias: Attic | Motion | Lights on
  trigger:
    platform: state
    entity_id: binary_sensor.attic_motion_detected
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.attic_dark_enough
        state: 'on'
      - condition: time
        after: '06:00:00'
        before: '02:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.lg_attic_all
        brightness_pct: 70
        kelvin: 2700
