- alias: Attic | Motion | Lights off
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_attic
    to: 'off'
    for:
      minutes: 20
  action:
    - service: light.turn_off
      entity_id: light.attic
