- id: matrix_001
  alias: matrix_001
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: help
  action:
    service: notify.notify_matrix_clean
    data_template:
      message: "Possible commands:\n
                - Who are you?\n
                - Light em up!\n
                - Cut all power\n
                - Cut socket one\n
                - Cut socket two\n
                - Cut socket three\n
                - reel_in_the_sunscreen\n
                - Attic shutters up\n
                - Attic shutters down\n
                - Cheapest local gas\n
                - Show me the yield\n
                \n
                So what will it be?"


- id: matrix_002
  alias: matrix_002
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: introduction
  action:
    service: notify.notify_matrix_clean
    data_template:
      message: "My name is Hassi-o, servant of men ruler of tech."


- id: matrix_003
  alias: matrix_003
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: light_em_up
  action:
    - service: switch.turn_ion
      entity_id:
        - switch.0x000d6ffffedad23c_switch
        - switch.0x000d6ffffea6df64_switch
        - switch.0x000d6ffffedaf667_switch
        - switch.0x000d6ffffedc5e05_switch
    - service: script.turn_on
      entity_id:
        - script.scene_sa_not_watching_tv
        - script.scene_kitchen_night
        - script.scene_ex_night
    - service: notify.notify_matrix_clean
      data:
        message: "Shining bright like a diamond!"


- id: matrix_004
  alias: matrix_004
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_socket_one
  action:
    - service: switch.turn_off
      entity_id: switch.0x000d6ffffedad23c_switch
    - service: notify.notify_matrix_clean
      data:
        message: "Socket one killed!"


- id: matrix_005
  alias: matrix_005
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_socket_two
  action:
    - service: switch.turn_off
      entity_id: switch.0x000d6ffffea6df64_switch
    - service: notify.notify_matrix_clean
      data:
        message: "Socket two killed!"


- id: matrix_006
  alias: matrix_006
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_socket_three
  action:
    - service: switch.turn_off
      entity_id: switch.0x000d6ffffea6e967_switch
    - service: notify.notify_matrix_clean
      data:
        message: "Socket three killed!"


- id: matrix_007
  alias: matrix_007
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_socket_five
  action:
    - service: switch.turn_off
      entity_id: switch.0x000d6ffffedaf667_switch
    - service: notify.notify_matrix_clean
      data:
        message: "Socket five killed!"


- id: matrix_008
  alias: matrix_008
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_socket_six
  action:
    - service: switch.turn_off
      entity_id: switch.0x000d6ffffedc5e05_switch
    - service: notify.notify_matrix_clean
      data:
        message: "Socket six killed!"


- id: matrix_009
  alias: matrix_009
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_all_power
  action:
    - service: switch.turn_off
      entity_id:
        - switch.0x000d6ffffedad23c_switch
        - switch.0x000d6ffffea6df64_switch
        - switch.0x000d6ffffea6e967_switch
        - switch.0x000d6ffffedaf667_switch
        - switch.0x000d6ffffedc5e05_switch
    - service: notify.notify_matrix_clean
      data:
        message: "I've cut the power as you requested!"


- id: matrix_010
  alias: matrix_010
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: reel_in_the_sunscreen
  action:
    - service: switch.turn_off
      entity_id: switch.sunscreen
    - service: notify.notify_matrix_clean
      data:
        message: "As you wish! May the Sun shine freely!"


- id: matrix_011
  alias: matrix_011
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: attic_shutters_up
  action:
    - service: cover.open_cover
      entity_id: cover.attic_shutters


- id: matrix_012
  alias: matrix_012
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: attic_shutters_down
  action:
    - service: cover.close_cover
      entity_id: cover.attic_shutters


- id: matrix_013
  alias: matrix_013
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: show_gas_prices
  action:
    - service: notify.notify_matrix_clean
      data:
        message: "Today's gas prices: \nTi (E5): €{{ states('sensor.gas_station_1_euro95') }} \nFi (E5): €{{ states('sensor.gas_station_2_euro95') }} \nTa (E5): €{{ states('sensor.gas_station_3_euro95') }}"


- id: matrix_014
  alias: matrix_014
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: show_solar_yield
  action:
    - service: notify.notify_matrix_clean
      data:
        message: "Today's yield: {{ states('sensor.daily_yield') }} Wh \nTotal yield: {{ states('sensor.total_yield') }} kWh"


- id: matrix_015
  alias: matrix_015
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: front_door_is_closed
  action:
    - service: switch.turn_off
      entity_id: switch.sunscreen
    - service: notify.notify_matrix_clean
      data:
        message: "Manually acknowledged front-door is closed"
