- alias: 'Matrix | React to help'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: help
  action:
    service: notify.notify_matrix_clean
    data_template:
      message: "Possible commands:\n
                - Who are you?\n
                - Light em up!\n
                - Cut all power\n
                - Cut socket one\n
                - Cut socket two\n
                - Cut socket three\n
                - reel_in_the_sunscreen\n
                - Attic shutters up\n
                - Attic shutters down\n
                - Cheapest local gas\n
                - Show me the yield\n
                \n
                So what will it be?"


- alias: 'Matrix | React to an introduction'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: introduction
  action:
    service: notify.notify_matrix_clean
    data_template:
      message: "My name is Hassi-o, servant of men ruler of tech."


- alias: 'Matrix | Turn on all the things'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: light_em_up
  action:
    - service: switch.turn_ion
      entity_id:
        - switch.0x000d6ffffedad23c_switch
        - switch.0x000d6ffffea6df64_switch
        - switch.0x000d6ffffedaf667_switch
        - switch.0x000d6ffffedc5e05_switch
    - service: scene.turn_on
      entity_id:
        - scene.sa_not_watching_tv
        - scene.kitchen_relax
        - scene.ex_relax
    - service: notify.notify_matrix_clean
      data:
        message: "Shining bright like a diamond!"


- alias: 'Matrix | React to Cut socket one'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_socket_one
  action:
    - service: switch.turn_off
      entity_id: switch.0x000d6ffffedad23c_switch
    - service: notify.notify_matrix_clean
      data:
        message: "Socket one killed!"


- alias: 'Matrix | React to Cut socket two'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_socket_two
  action:
    - service: switch.turn_off
      entity_id: switch.0x000d6ffffea6df64_switch
    - service: notify.notify_matrix_clean
      data:
        message: "Socket two killed!"


- alias: 'Matrix | React to Cut socket three'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_socket_three
  action:
    - service: switch.turn_off
      entity_id: switch.0x000d6ffffea6e967_switch
    - service: notify.notify_matrix_clean
      data:
        message: "Socket three killed!"


- alias: 'Matrix | React to Cut socket five'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_socket_five
  action:
    - service: switch.turn_off
      entity_id: switch.0x000d6ffffedaf667_switch
    - service: notify.notify_matrix_clean
      data:
        message: "Socket five killed!"


- alias: 'Matrix | React to Cut socket six'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_socket_six
  action:
    - service: switch.turn_off
      entity_id: switch.0x000d6ffffedc5e05_switch
    - service: notify.notify_matrix_clean
      data:
        message: "Socket six killed!"


- alias: 'Matrix | React to Cut all power'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: cut_all_power
  action:
    - service: switch.turn_off
      entity_id:
        - switch.0x000d6ffffedad23c_switch
        - switch.0x000d6ffffea6df64_switch
        - switch.0x000d6ffffea6e967_switch
        - switch.0x000d6ffffedaf667_switch
        - switch.0x000d6ffffedc5e05_switch
    - service: notify.notify_matrix_clean
      data:
        message: "I've cut the power as you requested!"


- alias: 'Matrix | React to !reel_in_the_sunscreen'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: reel_in_the_sunscreen
  action:
    - service: switch.turn_off
      entity_id: switch.sun_screen
    - service: notify.notify_matrix_clean
      data:
        message: "As you wish! May the Sun shine freely!"


- alias: 'Matrix | React to Attic shutters up'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: attic_shutters_up
  action:
    - service: cover.open_cover
      entity_id: cover.attic_shutters


- alias: 'Matrix | React to Attic shutters down'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: attic_shutters_down
  action:
    - service: cover.close_cover
      entity_id: cover.attic_shutters


- alias: 'Matrix | React to Cheapest local gas'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: show_gas_prices
  action:
    - service: notify.notify_matrix_clean
      data:
        message: "Today's gas prices: \nTi (E5): €{{ states('sensor.gas_station_1_euro95') }} \nFi (E5): €{{ states('sensor.gas_station_2_euro95') }} \nTa (E5): €{{ states('sensor.gas_station_3_euro95') }}"


- alias: 'Matrix | React to Show me the yield'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: show_solar_yield
  action:
    - service: notify.notify_matrix_clean
      data:
        message: "Today's yield: {{ states('sensor.daily_yield') }} Wh \nTotal yield: {{ states('sensor.total_yield') }} kWh"


- alias: 'Matrix | React to Confirmed front-door is closed'
  trigger:
    platform: event
    event_type: matrix_command
    event_data:
      command: front_door_is_closed
  action:
    - service: switch.turn_off
      entity_id: switch.sun_screen
    - service: notify.notify_matrix_clean
      data:
        message: "Manually acknowledged front-door is closed"
