- alias: HW | Darkness cutoff | On
  trigger:
    platform: time_pattern
    minutes: '/5'
    seconds: 00
  condition:
    condition: numeric_state
    entity_id: sensor.illumination_in_hallway_stairs
    below: 18
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.hw_meets_darkness_cutoff


- alias: HW | Darkness cutoff | Off
  trigger:
    platform: time_pattern
    minutes: '/5'
    seconds: 00
  condition:
    condition: numeric_state
    entity_id: sensor.illumination_in_hallway_stairs
    above: 18
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.hw_meets_darkness_cutoff
