- alias: MB | Motion | Lights off
  initial_state: True
  trigger:
    - platform: state
      entity_id: sensor.motion_in_corridor
      to: '0'
      for:
        minutes: 0
    - platform: state
      entity_id: sensor.motion_in_corridor
      to: '0'
      for:
        minutes: 0
  action:
    - service: homeassistant.turn_off
      entity_id: light.master_bedroom
