- alias: MB | Motion | Lights off
  trigger:
    - platform: state
      entity_id: sensor.motion_in_corridor
      to: '0'
      for:
        minutes: 0
    - platform: state
      entity_id: sensor.motion_in_corridor
      to: '0'
      for:
        minutes: 0
  action:
    - service: light.turn_off
      entity_id: light.lg__mb__all
