- alias: MB | Duo switch | right | On
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "on", "entity_id": "switch.duo_switch_mb_r"}
  action:
    - service: light.turn_on
      data:
        entity_id: light.lg_mb_all
        transition: 1
        brightness_pct: 100
        kelvin: 2700

- alias: MB | Duo switch | right | Off
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "off", "entity_id": "switch.duo_switch_mb_r"}
  action:
    - service: light.turn_off
      entity_id: light.lg_mb_all
