- alias: MB | Single switch | On
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "on", "entity_id": "switch.single_switch_mb"}
  action:
    - service: light.turn_on
      data:
        entity_id: light.lg__mb__all
        transition: 1
        brightness_pct: 50
        kelvin: 2700


- alias: MB | Single switch | Off
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "off", "entity_id": "switch.single_switch_mb"}
  action:
    - service: light.turn_off
      entity_id: light.lg__mb__all
