- alias: MB | Single switch | On
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "on", "entity_id": "switch.single_switch_mb"}
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: "Master Bedroom"
      scene_name: "MB | Sleep"


- alias: MB | Single switch | Off
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "off", "entity_id": "switch.single_switch_mb"}
  action:
    - service: homeassistant.turn_off
      entity_id: light.innr_master_bedroom
