- alias: MB | Duo switch | left | On
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "on", "entity_id": "switch.duo_switch_mb_l"}
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: "Master Bedroom"
      scene_name: "MB | Sleep"


- alias: MB | Duo switch | left | Off
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "off", "entity_id": "switch.duo_switch_mb_l"}
  action:
    - service: homeassistant.turn_off
      entity_id: light.innr__master_bedroom
