- id: smoke_001
  alias: smoke_001
  trigger:
    platform: state
    entity_id:
      - binary_sensor.lr_smoke_detected
      - binary_sensor.lb_smoke_detected
      - binary_sensor.sb_smoke_detected
    to: 'on'
  action:
    - service: notify.send_mail
      data_template:
        title: "SMOKE ALARM: {{ state_attr(trigger.entity_id, 'friendly_name') }}"
        message: "Smoke was detected in the {{ state_attr(trigger.entity_id, 'friendly_name') }}!!\n
                  Time of detection: {{ now().strftime('%H:%M') }}\n
                  Verify and/or call the emergency services!"
    - service: notify.notify_matrix_clean
      data_template:
        message: "-----------------------------------------------\n
                  | Smoke has been detected in the {{ state_attr(trigger.entity_id, 'friendly_name') }}! |\n
                  -----------------------------------------------"
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if state_attr(trigger.entity_id, 'friendly_name') == 'Living Room' %}
            script.scene_lr_search_mode
          {% elif state_attr(trigger.entity_id, 'friendly_name') == 'Large Bedroom' %}
            script.scene_lb_search_mode
          {% elif state_attr(trigger.entity_id, 'friendly_name') == 'Small Bedroom' %}
            script.scene_sb_search_mode
          {% endif %}


- id: Smoke Alarm | LR | Test
  alias: Smoke Alarm | LR | Test
  trigger:
    platform: event
    event_type: my_bs_event
  action:
    - service: mqtt.publish
      data:
        payload: "{\"selftest\": \"\"}"
        topic: zigbee2mqtt/0x00158d0003612f9b/set
    - service: homeassistant.turn_on
      entity_id: binary_sensor.lr_smoke_detected


- id: Smoke Alarm | LB | Test
  alias: Smoke Alarm | LB | Test
  trigger:
    platform: event
    event_type: my_bs_event
  action:
    - service: mqtt.publish
      data:
        payload: "{\"selftest\": \"\"}"
        topic: zigbee2mqtt/0x00158d00045cd482/set
    - service: homeassistant.turn_on
      entity_id: binary_sensor.lb_smoke_detected


- id: Smoke Alarm | SB | Test
  alias: Smoke Alarm | SB | Test
  trigger:
    platform: event
    event_type: my_bs_event
  action:
    - service: mqtt.publish
      data:
        payload: "{\"selftest\": \"\"}"
        topic: zigbee2mqtt/0x00158d0004117f6f/set
    - service: homeassistant.turn_on
      entity_id: binary_sensor.sb_smoke_detected
