- alias: LR | Smoke Detected | Notify | Light
  trigger:
    - platform: state
      entity_id: binary_sensor.lr_smoke_detected
      to: 'on'
  action:
    - service: notify.notify_matrix_clean
      data:
        message: "-----------------------------------------------\n
                  | Smoke has been detected in the Living Room! |\n
                  -----------------------------------------------"
    - service: scene.turn_on
      entity_id: scene.lr_search_mode_on


- alias: LB | Smoke Detected | Notify | Light
  trigger:
    - platform: state
      entity_id: binary_sensor.lb_smoke_detected
      to: 'on'
  action:
    - service: notify.notify_matrix_clean
      data:
        message: "-------------------------------------------------\n
                  | Smoke has been detected in the Large Bedroom! |\n
                  -------------------------------------------------"
    - service: scene.turn_on
      entity_id: scene.lb_search_mode_on
