- alias: LR | Smoke Detected | Notify | Light
  trigger:
    platform: state
    entity_id: binary_sensor.lr_smoke_detected
    to: 'on'
  action:
    - service: notify.send_mail
      data:
        title: "SMOKE ALARM: Living Room"
        message: "Smoke was detected in the living room!!\n
                  Time of detection: {{ now().strftime('%H:%M') }}\n
                  Verify and/or call the emergency services!"
    - service: notify.notify_matrix_clean
      data:
        message: "-----------------------------------------------\n
                  | Smoke has been detected in the Living Room! |\n
                  -----------------------------------------------"
    - service: scene.turn_on
      entity_id: scene.lr_search_mode


- alias: LB | Smoke Detected | Notify | Light
  trigger:
    platform: state
    entity_id: binary_sensor.lb_smoke_detected
    to: 'on'
  action:
    - service: notify.send_mail
      data:
        title: "SMOKE ALARM: Large Bedroom"
        message: "Smoke was detected in the large bedroom!!\n
                  Time of detection: {{ now().strftime('%H:%M') }}\n
                  Verify and/or call the emergency services!"
    - service: notify.notify_matrix_clean
      data:
        message: "-------------------------------------------------\n
                  | Smoke has been detected in the Large Bedroom! |\n
                  -------------------------------------------------"
    - service: scene.turn_on
      entity_id: scene.lb_search_mode
