- id: smoke_001
  alias: smoke_001
  trigger:
    platform: state
    entity_id:
      - binary_sensor.lr_smoke_detected
      - binary_sensor.lb_smoke_detected
    to: 'on'
  action:
    - service: notify.send_mail
      data_template:
        title: "SMOKE ALARM: {{ state_attr(trigger.entity_id, 'friendly_name') }}"
        message: "Smoke was detected in the {{ state_attr(trigger.entity_id, 'friendly_name') }}!!\n
                  Time of detection: {{ now().strftime('%H:%M') }}\n
                  Verify and/or call the emergency services!"
    - service: notify.notify_matrix_clean
      data_template:
        message: "-----------------------------------------------\n
                  | Smoke has been detected in the {{ state_attr(trigger.entity_id, 'friendly_name') }}! |\n
                  -----------------------------------------------"
    - service: scene.turn_on
      data_template:
        entity_id: >
          {% if is_state('trigger.entity_id', 'binary_sensor.lr_smoke_detected') %}
            scene.lr_search_mode
          {% else %}
            scene.lb_search_mode
          {% endif %}


# - alias: LB | Smoke Detected | Notify | Light
#   trigger:
#     platform: state
#     entity_id: binary_sensor.lb_smoke_detected
#     to: 'on'
#   action:
#     - service: notify.send_mail
#       data:
#         title: "SMOKE ALARM: Large Bedroom"
#         message: "Smoke was detected in the large bedroom!!\n
#                   Time of detection: {{ now().strftime('%H:%M') }}\n
#                   Verify and/or call the emergency services!"
#     - service: notify.notify_matrix_clean
#       data:
#         message: "-------------------------------------------------\n
#                   | Smoke has been detected in the Large Bedroom! |\n
#                   -------------------------------------------------"
#     - service: scene.turn_on
#       entity_id: scene.lb_search_mode
