- platform: template
  sensors:
    lr_smoke_detected:
      value_template: >-
        {{ is_state('binary_sensor.smoke_living_room_smoke', 'on') }}

    lb_smoke_detected:
      value_template: >-
        {{ is_state('binary_sensor.smoke_large_bedroom_smoke', 'on') }}

    sb_smoke_detected:
      value_template: >-
        {{ is_state('binary_sensor.smoke_small_bedroom_smoke', 'on') }}
