- platform: template
  sensors:
    lr_smoke_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x00158d0003612f9b_smoke', 'on') }}

    lb_smoke_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x00158d00045cd482_smoke', 'on') }}

    sb_smoke_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x00158d0004117f6f_smoke', 'on') }}
