living_room_lighting:
  name: Living room lighting
  entities:
    - light.kitchen
    - light.sitting_area
    - light.ledstrip_tv_cabinet

corridor_lighting:
  name: Corridor lighting
  entities:
    - light.corridor

master_bedroom_lighting:
  name: Master Bedroom lighting
  entities:
    - light.master_bedroom

living_room_climate:
  name: Living room climate
  entities:
    - climate.living_room
    - sensor.temperature_in_hallwaydoor
    - sensor.temperature_in_hallwaystairs
    - sensor.temperature_in_sitting_area
    - sensor.temperature_in_kitchen
    - sensor.illumination_in_hallwaydoor
    - sensor.illumination_in_hallwaystairs
    - sensor.illumination_in_sitting_area
    - sensor.illumination_in_kitchen

first_floor_climate:
  name: First floor climate
  entities:
    - sensor.temperature_in_corridor
    - sensor.illumination_in_corridor

media_players:
  name: Media player
  entities:
    - media_player.yamaha_receiver
    - media_player.living_room
    - media_player.living_room_audio
    - media_player.kodi

hallway_lighting:
  name: Hallway lighting
  entities:
    - light.hallway

all_ground_floor_lights:
  name: All ground floor lights
  entities:
    - light.hue__bulb__kitchen_table__l
    - light.hue__bulb__kitchen_table__r
    - light.hue__bulb__standing_lamp
    - light.hue__iris__tv_cabinet
    - light.ledstrip_tv_cabinet
    - light.innr__downstairs__hallway

all_first_floor_lights:
  name: All first floor lights
  entities:
    - light.innr__corridor
    - light.innr__master_bedroom

internet_health_check:
  name: Internet health check
  entities:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.speedtest_ping

automation:
  name: Automations
  entities:
    - automation.turn_on_the_hallway_light_when_there_is_movement_and_its_dark
    - automation.turn_off_the_hallway_light_5_minutes_after_last_movement
    - automation.turn_on_the_sitting_area_lights_when_there_is_movement_and_its_dark
    - automation.reevaluate_lighting_in_sitting_area_periodically_and_turn_on_accordingly
    - automation.reevaluate_lighting_in_sitting_area_periodically_and_turn_off_accordingly
    - automation.turn_off_the_sitting_area_lights_10_minutes_after_last_movement
    - automation.turn_on_the_kitchen_lights_when_there_is_movement_and_its_dark
    - automation.reevaluate_lighting_in_kitchen_periodically_and_turn_on_accordingly
    - automation.reevaluate_lighting_in_kitchen_periodically_and_turn_off_accordingly
    - automation.turn_off_the_kitchen_lights_10_minutes_after_last_movement
    - automation.turn_on_the_corridor_light_when_there_is_movement_and_its_dark
    - automation.turn_off_the_corridor_light_5_minutes_after_last_movement
    - automation.turn_on_the_master_bedroom_light_when_there_is_movement_and_its_dark
    - automation.turn_off_the_master_bedroom_light_5_minutes_after_last_movement

exterior:
  name: Exterior
  entities:
    - sensor.dark_sky_summary
    - sensor.dark_sky_temperature
    - sensor.dark_sky_apparent_temperature
    - sensor.dark_sky_wind_speed

hidden_crap:
  name: Hidden crap
  entities:
    - light.kitchen_do_not_use
    - light.living_room_do_not_use
    - light.downstairs_hallway_do_not_use
    - light.living_room
    - group.living_room
