living_room_lighting:
  name: Living room lighting
  entities:
    - light.kitchen
    - light.sitting_area

living_room_climate:
  name: Living room climate
  entities:
    - climate.living_room
    - sensor.temperature_in_hallwaydoor
    - sensor.temperature_in_hallwaystairs
    - sensor.temperature_in_sitting_area
    - sensor.illumination_in_hallwaydoor
    - sensor.illumination_in_hallwaystairs
    - sensor.illumination_in_sitting_area

media_players:
  name: Media player
  entities:
    - media_player.kodi
    - media_player.yamaha_receiver

hallway_lighting:
  name: Hallway lighting
  entities:
    - light.hallway

all_ground_floor_lights:
  name: All ground floor lights
  entities:
    - light.hue__bulb__kitchen_table__l
    - light.hue__bulb__kitchen_table__r
    - light.hue__bulb__standing_lamp
    - light.hue__iris__tv_cabinet
    - light.innr__downstairs__hallway

internet_health_check:
  name: Internet health check
  entities:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.speedtest_ping

automation:
  name: Automation
  entities:
    - automation.turn_off_the_hallway_light_2_minutes_after_last_movement
    - automation.turn_on_the_hallway_light_when_there_is_movement

exterior:
  name: Exterior
  entities:
    - sensor.dark_sky_summary
    - sensor.dark_sky_temperature
    - sensor.dark_sky_apparent_temperature
    - sensor.dark_sky_wind_speed

hidden_crap:
  name: Hidden crap
  entities:
    - light.kitchen_do_not_use
    - light.living_room_do_not_use
    - light.downstairs_hallway_do_not_use
    - light.living_room
    - group.living_room
