- alias: Smoke Alarm | LR | Test
  trigger:
    platform: event
    event_type: my_bs_event
  action:
    - service: mqtt.publish
      data:
        payload: "{\"selftest\": \"\"}"
        topic: zigbee2mqtt/0x00158d0003612f9b/set


- alias: Smoke Alarm | LB | Test
  trigger:
    platform: event
    event_type: my_bs_event
  action:
    - service: mqtt.publish
      data:
        payload: "{\"selftest\": \"\"}"
        topic: zigbee2mqtt/0x00158d00045cd482/set
