homeassistant:
  customize: !include customize.yaml

device_tracker: !include device_tracker.yaml

person:
  - name: !secret person_one_name
    id: !secret person_one_user_id
    device_trackers:
      - device_tracker.phone_person_one
  - name: !secret person_two_name
    id: !secret person_two_user_id
    device_trackers:
      - device_tracker.phone_person_two

binary_sensor: !include binary_sensor.yaml
