- platform: template
  sensors:
    person_one_home:
      value_template: >-
        {{ is_state('device_tracker.phone_person_one', 'home') }}

    person_two_home:
      value_template: >-
        {{ is_state('device_tracker.phone_person_two', 'home') }}

    occupants_home:
      value_template: >-
        {{ is_state('binary_sensor.person_one_home', 'on') 
           or is_state('binary_sensor.person_two_home', 'on') }}

    hw_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x00178801020260c3_occupancy', 'on')
           or is_state('binary_sensor.0x00178801020282bc_occupancy', 'on') }}

    toilet_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x00158d000447edb4_occupancy', 'on') }}

    sa_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x0017880102026161_occupancy', 'on')
           or is_state('binary_sensor.0x00158d00034911fc_occupancy', 'on')
           or is_state('binary_sensor.kaku_motion_sa', 'on') }}

    kitchen_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x0017880102030677_occupancy', 'on')
           or is_state('binary_sensor.0x00158d00033a43ef_occupancy', 'on') }}

    lr_motion_detected:
    value_template: >-
      {{ is_state('binary_sensor.sa_motion_detected', 'on')
          or is_state('binary_sensor.kitchen_motion_detected', 'on') }}

    co_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x00178801020357e5_occupancy', 'on') }}

    mb_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x00158d00044c977b_occupancy', 'on') }}

    bathroom_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x00158d000349234a_occupancy', 'on')
           or is_state('binary_sensor.0x00158d00033aac53_occupancy', 'on')
           or is_state('binary_sensor.0x00158d00044d28cf_occupancy', 'on')
           or is_state('binary_sensor.0x680ae2fffe367f3b_occupancy', 'on') }}

    lb_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x00158d00044d216c_occupancy', 'on') }}

    sb_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x00158d00044d34de_occupancy', 'on') }}
        
    attic_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x00158d00036b62d0_occupancy', 'on')
           or is_state('binary_sensor.0x00158d000302ec77_occupancy', 'on') }}

    office_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x00158d0004499f26_occupancy', 'on') }}
      
    backyard_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x001788010647ff92_occupancy', 'on') }}

        