- platform: template
  sensors:
    person_one_home:
      value_template: >-
        {{ is_state('device_tracker.phone_person_one', 'home') }}

    person_two_home:
      value_template: >-
        {{ is_state('device_tracker.phone_person_two', 'home') }}

    occupants_home:
      value_template: >-
        {{ is_state('binary_sensor.person_one_home', 'on') 
           or is_state('binary_sensor.person_two_home', 'on') }}

    hw_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x00178801020260c3_occupancy', 'on')
           or is_state('binary_sensor.0x00178801020282bc_occupancy', 'on') }}

    toilet_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.motion_toilet_occupancy', 'on') }}

    sa_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x0017880102026161_occupancy', 'on')
           or is_state('binary_sensor.motion_sitting_area_closet_occupancy', 'on')
           or is_state('binary_sensor.0x0017880102030677_occupancy', 'on')
           or is_state('binary_sensor.0x0017880102026161_occupancy', 'on') }}

    kitchen_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x0017880102030677_occupancy', 'on')
           or is_state('binary_sensor.motion_kitchen_front_occupancy', 'on') }}

    lr_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.sa_motion_detected', 'on')
            or is_state('binary_sensor.kitchen_motion_detected', 'on') }}

    co_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x00178801020357e5_occupancy', 'on') }}

    mb_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.motion_master_bedroom_occupancy', 'on') }}

    bathroom_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.motion_bathroom_back_occupancy', 'on')
           or is_state('binary_sensor.motion_bathroom_front_occupancy', 'on')
           or is_state('binary_sensor.motion_bathroom_shower_occupancy', 'on')
           or is_state('binary_sensor.0x680ae2fffe367f3b_occupancy', 'on') }}

    lb_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.motion_large_bedroom_occupancy', 'on') }}

    sb_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.motion_small_bedroom_occupancy', 'on') }}
        
    attic_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x00158d00036b62d0_occupancy', 'on')
           or is_state('binary_sensor.motion_attic_front_occupancy', 'on') }}

    office_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.motion_office_front_occupancy', 'on')
           or is_state('binary_sensor.motion_office_back_occupancy', 'on') }}
      
    backyard_motion_detected:
      value_template: >-
        {{ is_state('binary_sensor.0x001788010647ff92_occupancy', 'on') }}

        