- platform: workday
  name: Working person one
  country: NL
  workdays: !secret person_one_workdays

- platform: workday
  name: Working person two
  country: NL
  workdays: !secret person_two_workdays

- platform: tod
  name: Early Morning
  after: '07:00'
  before: '09:59'

- platform: tod
  name: Late Morning
  after: '10:00'
  before: '11:59'

- platform: tod
  name: Early Afternoon
  after: '12:00'
  before: '14:59'

- platform: tod
  name: Late Afternoon
  after: '15:00'
  before: '17:59'

- platform: tod
  name: Early Evening
  after: '18:00'
  before: '19:59'

- platform: tod
  name: Late Evening
  after: '20:00'
  before: '22:29'

- platform: tod
  name: Early Night
  after: '22:30'
  before: '02:59'

- platform: tod
  name: Late Night
  after: '03:00'
  before: '06:59'

- platform: template
  sensors:
    front_door_open:
      value_template: >-
        {{ is_state('binary_sensor.contact_front_door_contact', 'on') }}

    kitchen_window_open:
      value_template: >-
        {{ is_state('binary_sensor.contact_kitchen_window_contact', 'on') }}

    back_door_open:
      value_template: >-
        {{ is_state('binary_sensor.contact_back_door_contact', 'on') }}

    lr_door_or_window_open:
      value_template: >-
        {{ is_state('binary_sensor.kitchen_window_open', 'on')
          or is_state('binary_sensor.back_door_open', 'on') }}

# # Temporary workaround until TOD is fixed:
# template:
# - binary_sensor:
#   - name: Night Time
#     unique_id: night_time
#     state: >
#       {{ not '06:30' <= as_timestamp(now()) | timestamp_custom('%H:%M') <= '23:00' }}