- alias: Traffic | Train | Delays
  trigger:
    platform: state
    entity_id: sensor.train_home_to_work.attributes.departure_delay
    # entity_id: states.sensor.train_home_to_work.attributes.departure_delay
    to: 'True'
  action:
    service: notify.matrix_notify
    data_template:
      message: "Your train has a delay"
