- platform: moon

- platform: template
  sensors:
    moon_phase:
      entity_id: sensor.moon
      friendly_name: 'Moon phase'
      value_template: '{{ states.sensor.moon.state }}'
      entity_picture_template: /local/moon_phases/{{ states.sensor.moon.state }}.svg
