- platform: moon

- platform: template
  sensors:
    moon_phase_image:
      entity_id: sensor.moon
      friendly_name: 'Moon phase image'
      value_template: '/local/moon_phases/{{ states.sensor.moon.state }}.svg'
