# - id: Time | Dafang | Reboot
#   alias: Time | Dafang | Reboot
#   trigger:
#     platform: time
#     at: "2:05:00"
#   action:
#     service: shell_command.reboot_dafang


# - id: Time | Xiaofang 1 | Reboot
#   alias: Time | Xiaofang 1 | Reboot
#   trigger:
#     platform: time
#     at: "2:10:00"
#   action:
#     service: shell_command.reboot_xiaofang_1


# - id: Time | Xiaofang 2 | Reboot
#   alias: Time | Xiaofang 2 | Reboot
#   trigger:
#     platform: time
#     at: "2:15:00"
#   action:
#     service: shell_command.reboot_xiaofang_2
