- alias: HW | Motion | Lights off
  trigger:
    - platform: state
      entity_id: binary_sensor.hw_motion_detected
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: binary_sensor.hw_dark_enough
      to: 'off'
      for:
        minutes: 5
  action:
    - service: homeassistant.turn_off
      entity_id: light.hallway
