- alias: HW | Motion | Lights on
  trigger:
    - platform: state
      entity_id: sensor.motion_in_hallwaydoor
      to: '1'
    - platform: state
      entity_id: sensor.motion_in_hallwaystairs
      to: '1'
  condition:
    condition: state
    entity_id: input_boolean.hw_meets_darkness_cutoff
    state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: light.hallway
    # - service: notify.pushbullet
    #   data_template:
    #     title: "Home Assistant"
    #     message: "Hallway turned on with lux {{ states.sensor.illumination_in_hallwaystairs.state }}"
