- alias: HW | Motion | Lights on
  trigger:
    - platform: state
      entity_id: binary_sensor.hw_motion_detected
      to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.hw_dark_enough
    state: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Hallway"
        scene_name: "HW | Relax"
