- alias: HW | Motion | Lights off
  trigger:
    platform: time_pattern
    minutes: '/1'
    seconds: 00
  condition:
    condition: state
    entity_id: binary_sensor.hw_motion_detected
    state: 'off'
    for:
      minutes: 5
  action:
    - service: homeassistant.turn_off
      entity_id: light.hallway
