homeassistant:
  customize: !include customize.yaml

media_player: !include media_player.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include boolean.yaml
automation: !include automation.yaml
# script: !include script.yaml

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

cast:
  chromecast:
  - host: 10.0.221.26
  chromecast_audio:
  - host: 10.0.221.29

samsungtv:
  - name: samsung_tv
    host: !secret smart_tv_ip
    turn_on_action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: !secret smart_tv_mac
