- platform: kodi
  host: 10.0.221.11
  username: !secret kodi_username
  password: !secret kodi_password

- platform: yamaha
  host: 10.0.221.23

- platform: androidtv
  name: Xiaomi Tv Box
  host: 10.0.221.25
  exclude_unnamed_apps: true
  apps:
    org.xbmc.kodi: "Kodi"
    org.jellyfin.androidtv: "Jellyfin"
    com.netflix.ninja: "Netflix"
    com.spotify.tv.android: "Spotify"
    com.google.android.tvlauncher: "Homescreen"
    com.google.android.youtube.tv: "Youtube"

- platform: emby
  host: !secret jellyfin_host
  api_key: !secret jellyfin_api_key
  ssl: true