- platform: kodi
  host: 10.0.221.25
  username: !secret kodi_username
  password: !secret kodi_password

- platform: yamaha
  host: 10.0.221.23

- platform: samsungtv
  name: samsung_tv
  host: !secret smart_tv_ip
  turn_on_action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: !secret smart_tv_mac