- platform: sonarr_upcoming_media
  api_key: !secret sonarr_api_key
  host: !secret synology_ip
  port: 8989
  days: 2
  ssl: false
  max: 10

- platform: radarr_upcoming_media
  api_key: !secret radarr_api_key
  host: !secret synology_ip
  port: 8310
  days: 120
  ssl: false
  theaters: false
  max: 10

- platform: template
  sensors:
    xiaomi_app:
      friendly_name: "Xiaomi App"
      value_template: "{{ state_attr('media_player.xiaomi_tv_box', 'app_name') }}"
