- platform: sonarr
  api_key: !secret sonarr_api_key
  host: !secret sonarr_host
  port: 443
  monitored_conditions:
    - upcoming
  days: 2
  ssl: true

- platform: radarr
  api_key: !secret radarr_api_key
  host: !secret radarr_host
  port: 443
  monitored_conditions:
    - upcoming
  days: 120
  ssl: true

- platform: template
  sensors:
    xiaomi_app:
      friendly_name: "Xiaomi App"
      value_template: "{{ state_attr('media_player.xiaomi_tv_box', 'app_name') }}"
