- platform: sonarr_upcoming_media
  api_key: !secret sonarr_api_key
  host: !secret sonarr_host
  port: 443
  days: 2
  ssl: true

- platform: radarr_upcoming_media
  api_key: !secret radarr_api_key
  host: !secret radarr_host
  port: 443
  days: 120
  ssl: true
  theaters: false
  max: 10

- platform: template
  sensors:
    xiaomi_app:
      friendly_name: "Xiaomi App"
      value_template: "{{ state_attr('media_player.xiaomi_tv_box', 'app_name') }}"
