- alias: CO | Motion | Lights on
  trigger:
    platform: state
    entity_id: binary_sensor.co_motion_detected
    to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.co_dark_enough
    state: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Corridor"
        scene_name: "Co | Relax"
