- alias: CO | Motion | Light | Night
  trigger:
    platform: state
    entity_id: binary_sensor.co_motion_detected
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.co_dark_enough
        state: 'on'
      - condition: time
        after: '22:30:00'
        before: '07:30:00'
  action:
    - service: scene.turn_on
      entity_id: scene.co_night

- alias: CO | Motion | Light | Day
  trigger:
    platform: state
    entity_id: binary_sensor.co_motion_detected
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.co_dark_enough
        state: 'on'
      - condition: time
        after: '07:30:00'
        before: '22:30:00'
  action:
    - service: scene.turn_on
      entity_id: scene.co_relax
