- alias: CO | Motion | Lights off
  trigger:
    platform: state
    entity_id: binary_sensor.co_motion_detected
    to: 'off'
    for:
      minutes: 0
  action:
    - service: homeassistant.turn_off
      entity_id: light.corridor
