- alias: SA | Darkness cutoff | On
  trigger:
    platform: time
    minutes: '/5'
    seconds: 00
  condition:
    condition: numeric_state
    entity_id: sensor.illumination_in_sitting_area
    below: 18
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.sa_meets_darkness_cutoff


- alias: SA | Darkness cutoff | Off
  trigger:
    platform: time
    minutes: '/5'
    seconds: 00
  condition:
    condition: numeric_state
    entity_id: sensor.illumination_in_sitting_area
    above: 18
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.sa_meets_darkness_cutoff