- platform: template
  sensors:
    kitchen_desired_temperature:
      value_template: >-
        {{ states('sensor.motion_bathroom_back_temperature')|float >= states('input_number.kitchen_temperature_threshold')| int }}
    master_bedroom_desired_temperature:
      value_template: >-
        {{ states('sensor.motion_bathroom_back_temperature')|float >= states('input_number.master_bedroom_temperature_threshold')| int }}
    guest_bedroom_desired_temperature:
      value_template: >-
        {{ states('sensor.motion_bathroom_back_temperature')|float >= states('input_number.guest_bedroom_temperature_threshold')| int }}
