- alias: Kitchen | Time | Lights on
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_detected
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.kitchen_motion_detected
        state: 'on'
      - condition: state
        entity_id: binary_sensor.kitchen_dark_enough
        state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_relax
