- alias: Kitchen | Time | Lights on
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_detected
      to: 'on'
    - platform: time_pattern
      minutes: '/1'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.kitchen_motion_detected
        state: 'on'
      - condition: state
        entity_id: binary_sensor.kitchen_dark_enough
        state: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Kitchen"
        scene_name: "Kitchen | Relax"
    - service: light.turn_on
      data:
        entity_id: light.ledstrip_kitchen_cabinet
        rgb_color: [ 0, 7, 8 ]
        brightness: 8
