- alias: Kitchen | State | Lights off
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_detected
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.kitchen_dark_enough
      to: 'off'
      for:
        minutes: 5
  action:
    - service: homeassistant.turn_off
      entity_id: light.kitchen
    - service: light.turn_off
      entity_id: light.ledstrip_kitchen_cabinet
