- alias: Kitchen | Time | Lights on
  trigger:
    - platform: state
      entity_id: sensor.motion_in_kitchen
      to: '1'
    - platform: time_pattern
      minutes: '/5'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.motion_in_kitchen
        state: '1'
      - condition: state
        entity_id: input_boolean.kitchen_meets_darkness_cutoff
        state: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Kitchen"
        scene_name: "Kitchen | Relax"
