- alias: Kitchen | Time | Lights off
  trigger:
    platform: time_pattern
    minutes: '/1'
    seconds: 00
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.kitchen_motion_detected
        state: 'off'
        for:
          minutes: 5
      - condition: state
        entity_id: binary_sensor.kitchen_dark_enough
        state: 'off'
        for:
          minutes: 3
  action:
    - service: homeassistant.turn_off
      entity_id: light.kitchen
    - service: light.turn_off
      entity_id: light.ledstrip_kitchen_cabinet
