- alias: Kitchen | Motion | Lights on
  trigger:
    platform: state
    entity_id: sensor.motion_in_kitchen
    to: '1'
  condition:
    condition: state
    entity_id: input_boolean.kitchen_meets_darkness_cutoff
    state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: light.kitchen
