- alias: Re-evaluate lighting in kitchen periodically and turn off accordingly
  trigger:
    platform: time
    minutes: '/5'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.motion_in_kitchen
        state: '1'
      - condition: numeric_state
        entity_id: sensor.illumination_in_kitchen
        above: 18
      - condition: state
        entity_id: light.kitchen
        state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: light.kitchen