- alias: Kitchen | Time | Lights off
  trigger:
    platform: time
    minutes: '/15'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.motion_in_kitchen
        state: '1'
      - condition: state
        entity_id: input_boolean.sa_meets_darkness_cutoff
        state: 'off'
      - condition: state
        entity_id: light.kitchen
        state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: light.kitchen
