- alias: LB | Duo switch | right | On
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "on", "entity_id": "switch.duo_switch_lb_r"}
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: "Large Bedroom"
      scene_name: "LB | Relax"


- alias: LB | Duo switch | right | Off
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "off", "entity_id": "switch.duo_switch_lb_r"}
  action:
    - service: homeassistant.turn_off
      entity_id: light.hue__bulb__large_bedroom
