- alias: Large Bedroom | Duo switch | left | On
  initial_state: True
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "on", "entity_id": "switch.duo_switch_lb_l"}
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: "Large Bedroom"
      scene_name: "LB | Sleep"


- alias: Large Bedroom | Duo switch | left | Off
  initial_state: True
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "off", "entity_id": "switch.duo_switch_lb_l"}
  action:
    - service: homeassistant.turn_off
      entity_id: light.hue__bulb__large_bedroom
