- alias: LB | Duo switch | left | On
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "on", "entity_id": "switch.duo_switch_lb_l"}
  action:
    - service: scene.turn_on
      entity_id: scene.lb_night
    # - service: light.turn_on
    #   data:
    #     entity_id: light.dimmable_socket_two
    #     brightness_pct: 30


- alias: LB | Duo switch | left | Off
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "off", "entity_id": "switch.duo_switch_lb_l"}
  action:
    - service: light.turn_off
      entity_id: light.lg_lb_all
