- alias: LB | Duo switch | left | On
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "on", "entity_id": "switch.duo_switch_lb_l"}
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Large Bedroom"
        scene_name: "LB | Sleep"
    - service: switch.turn_on
      entity_id: switch.power_socket_three


- alias: LB | Duo switch | left | Off
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "off", "entity_id": "switch.duo_switch_lb_l"}
  action:
    - service: homeassistant.turn_off
      entity_id: light.hue_bulb_large_bedroom
    - service: switch.turn_off
      entity_id: switch.power_socket_three
