- alias: "LB | Time | Lights off"
  trigger:
    platform: state
    entity_id: light.hue__bulb__large_bedroom
    to: 'on'
    for:
      hours: 0
      minutes: 45
  action:
    service: homeassistant.turn_off
    entity_id: light.hue__bulb__large_bedroomsss
