- alias: "LB | Time | Lights off"
  trigger:
    platform: state
    entity_id: light.0x00178801039d140f_light
    to: 'on'
    for:
      hours: 0
      minutes: 45
  action:
    - service: light.turn_off
      entity_id: light.0x00178801039d140f_light


- alias: "LB | Time | Night lights off"
  trigger:
    platform: state
    entity_id: light.ledstrip_large_bedroom
    to: 'on'
    for:
      hours: 1
      minutes: 30
  action:
    - service: light.turn_off
      entity_id: light.ledstrip_large_bedroom
