- alias: "LB | Time | Lights off"
  trigger:
    platform: state
    entity_id: light.hue_bulb_large_bedroom
    to: 'on'
    for:
      hours: 0
      minutes: 45
  action:
    - service: homeassistant.turn_off
      entity_id: light.large_bedroom
    - service: notify.matrix_notify
      data:
        message: "I've Terminated the lights in the Large Bedroom."
