- alias: "LB | Time | Lights off"
  trigger:
    platform: state
    entity_id: light.hue_bulb_large_bedroom
    to: 'on'
    for:
      hours: 0
      minutes: 45
  action:
    - service: light.turn_off
      entity_id: light.0x00178801039d140f_light
    # - service: notify.notify_matrix_noisy
    #   data:
    #     message: "I've Terminated the lights in the Large Bedroom."


- alias: "LB | Time | Night lights off"
  trigger:
    platform: state
    entity_id: light.ledstrip_large_bedroom
    to: 'on'
    for:
      hours: 1
      minutes: 30
  action:
    - service: light.turn_off
      entity_id: light.ledstrip_large_bedroom
    # - service: homeassistant.turn_off
    #   entity_id: light.dimmable_socket_two
    # - service: notify.notify_matrix_noisy
    #   data:
    #     message: "I've Terminated the Night lights in the Large Bedroom."
