- alias: "Notify | State | LB Hue Bulb | Off"
  trigger:
    platform: state
    entity_id: light.hue_bulb_large_bedroom
    to: 'off'
  action:
    - service: notify.matrix_notify
      data:
        message: "Lights in Large Bedroom have been terminated!"


- alias: "Notify | State | LB Ledstrip | Off"
  trigger:
    platform: state
    entity_id: light.ledstrip_large_bedroom
    to: 'off'
  action:
    - service: notify.matrix_notify
      data:
        message: "The Night lights in the Large Bedroom are no more."


- alias: "Notify | State | SB Tradfri Bulb | Off"
  trigger:
    platform: state
    entity_id: light.tradfri_bulb_small_bedroom
    to: 'off'
  action:
    - service: notify.matrix_notify
      data:
        message: "Lights in Small Bedroom have been terminated!"


- alias: "Notify | State | SB Dim Socket | Off"
  trigger:
    platform: state
    entity_id: light.dimmable_socket_one
    to: 'off'
  action:
    - service: notify.matrix_notify
      data:
        message: "The Night lights in the Small Bedroom are no more."
