- alias: SA | Motion | Christmas Tree On
  trigger:
    - platform: state
      entity_id: sensor.motion_in_sitting_area
      to: '1'
    - platform: state
      entity_id: sensor.motion_in_kitchen
      to: '1'
  condition:
    condition: time
    after: '07:00:00'
    before: '03:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.power_socket_two
    - service: switch.turn_on
      entity_id: switch.power_socket_three
    - service: light.turn_on
      data:
        entity_id: light.dimmable_socket_one
        brightness: 35
    - service: light.turn_on
      data:
        entity_id: light.dimmable_socket_two
