- alias: SB | Duo switch | right | On
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "on", "entity_id": "switch.duo_switch_sb_r"}
  action:
    - service: scene.turn_on
      entity_id: scene.sb_day


- alias: SB | Duo switch | right | Off
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "off", "entity_id": "switch.duo_switch_sb_r"}
  action:
    - service: light.turn_off
      entity_id: light.lg_sb_all
