- alias: SB | Duo switch | left | On
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "on", "entity_id": "switch.duo_switch_sb_l"}
  action:
    - service: scene.turn_on
      entity_id: scene.sb_night

- alias: SB | Duo switch | left | Off
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "off", "entity_id": "switch.duo_switch_sb_l"}
  action:
    - service: light.turn_off
      entity_id: light.lg_sb_all
