- alias: "SB | Time | Lights off"
  trigger:
    platform: state
    entity_id: light.0x90fd9ffffeea4e5e_light
    to: 'on'
    for:
      hours: 0
      minutes: 45
  action:
    - service: light.turn_off
      entity_id: light.0x90fd9ffffeea4e5e_light


- alias: "SB | Time | Night lights off"
  trigger:
    platform: state
    entity_id: light.dimmable_socket_one
    to: 'on'
    for:
      hours: 1
      minutes: 30
  action:
    - service: light.turn_off
      entity_id: light.dimmable_socket_one
    - service: notify.notify_matrix_noisy
      data:
        message: "I've Terminated the Night lights in the Small Bedroom."


# This is a contingency to make sure it all turns off properly
- alias: 'SB | Time | Off'
  trigger:
    - platform: time
      at: '00:00:00'
  action:
    - service: light.turn_off
      entity_id: light.lg_sb_all
