- alias: "SB | Time | Lights off"
  trigger:
    platform: state
    entity_id: light.tradfri__bulb__small_bedroom
    to: 'on'
    for:
      hours: 0
      minutes: 45
  action:
    - service: homeassistant.turn_off
      entity_id: light.small_bedroom
    - service: notify.matrix_notify
      data:
        message: "I've Terminated the lights in the Small Bedroom."
