- alias: "SB | Time | Lights off"
  trigger:
    platform: state
    entity_id: light.tradfri_bulb_small_bedroom
    to: 'on'
    for:
      hours: 0
      minutes: 45
  action:
    - service: homeassistant.turn_off
      entity_id: light.small_bedroom
    - service: notify.matrix_notify
      data:
        message: "I've Terminated the lights in the Small Bedroom."


- alias: "SB | Time | Night lights off"
  trigger:
    - platform: time
      at: '23:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: light.dimmable_socket_one
    - service: notify.matrix_notify
      data:
        message: "I've Terminated the Night lights in the Small Bedroom."
