- alias: "SB | Time | Lights off"
  trigger:
    platform: state
    entity_id: light.0x90fd9ffffeea4e5e_light
    to: 'on'
    for:
      hours: 0
      minutes: 45
  action:
    - service: light.turn_off
      entity_id: light.lg__sb__all
    # - service: notify.notify_matrix_noisy
    #   data:
    #     message: "I've Terminated the lights in the Small Bedroom."


- alias: "SB | Time | Night lights off"
  trigger:
    platform: state
    entity_id: light.dimmable_socket_one
    to: 'on'
    for:
      hours: 1
      minutes: 30
  action:
    - service: homeassistant.turn_off
      entity_id: light.dimmable_socket_one
    - service: notify.notify_matrix_noisy
      data:
        message: "I've Terminated the Night lights in the Small Bedroom."
