title: Security
icon: mdi:cctv
cards:
  - !include ../cards/security/camera_dafang.yaml
  - !include ../cards/security/camera_xiaofang_1.yaml
  - !include ../cards/security/camera_xiaofang_2.yaml
  - !include ../cards/security/smoke.yaml
  - !include ../cards/security/contact_sensors.yaml
