- alias: LR | Boolean | Scene | Search Mode
  trigger:
    - platform: state
      entity_id: input_boolean.engage_search_mode
      to: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Living room"
        scene_name: "LR | Search Mode"
    - service: automation.turn_off
      entity_id: automation.sa_time_lights_off
    - service: automation.turn_off
      entity_id: automation.sa_tv_media_state_off
    - service: automation.turn_off
      entity_id: automation.sa_no_media
    - service: automation.turn_off
      entity_id:  automation.sa_media_playing_state_one
    - service: automation.turn_off
      entity_id:  automation.sa_media_playing_state_two
    - service: automation.turn_off
      entity_id: automation.kitchen_time_lights_off

- alias: LR | Boolean | Scene | Search Mode Off
  trigger:
    - platform: state
      entity_id: input_boolean.engage_search_mode
      to: 'off'
  action:
    - service: script.turn_on
      entity_id: script.scene_not_watching_tv
    - service: hue.hue_activate_scene
      data:
        group_name: "Kitchen"
        scene_name: "Kitchen | Relax"
    - service: automation.turn_on
      entity_id: automation.sa_time_lights_off
    - service: automation.turn_on
      entity_id: automation.sa_tv_media_state_off
    - service: automation.turn_on
      entity_id: automation.sa_no_media
    - service: automation.turn_on
      entity_id:  automation.sa_media_playing_state_one
    - service: automation.turn_on
      entity_id:  automation.sa_media_playing_state_two
    - service: automation.turn_on
      entity_id: automation.kitchen_time_lights_off
