- alias: SA | TV Media state | On
  trigger:
    - platform: state
      entity_id: media_player.living_room
      to: 'playing'
    - platform: state
      entity_id: media_player.kodi
      to: 'playing'
    - platform: state
      entity_id: input_boolean.sa_media_status_override
      to: 'on'

  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.sa_tv_media_playing


- alias: SA | TV Media state | Off
  trigger:
    - platform: state
      entity_id: media_player.living_room
      to: 'paused'
    - platform: state
      entity_id: media_player.kodi
      to: 'paused'
    - platform: state
      entity_id: media_player.living_room
      to: 'idle'
    - platform: state
      entity_id: media_player.kodi
      to: 'idle'
    - platform: state
      entity_id: input_boolean.sa_media_status_override
      to: 'off'
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.sa_tv_media_playing