- alias: Trigger media status override with hardware button
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "on", "entity_id": "switch.programmable_one"}

  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.sa_media_status_override


- alias: Trigger media status override with hardware button
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "off", "entity_id": "switch.programmable_one"}

  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.sa_media_status_override
