- alias: "Bathroom | Motion | Lights off"
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion_detected
      to: 'off'
      for:
        minutes: 15
  action:
    - service: light.turn_off
      entity_id: light.bathroom
    - service: notify.notify_matrix_noisy
      data:
        message: "Shame! You forgot the Bathroom lights again!"
