- alias: Bathroom | Duo switch | R | On | Night
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "on", "entity_id": "switch.duo_switch_bathroom_r"}
  condition:
    condition: time
    after: '22:30:00'
    before: '07:30:00'
  action:
    - service: scene.turn_on
      entity_id: scene.bathroom_r_night

- alias: Bathroom | Duo switch | R | On | Day
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "on", "entity_id": "switch.duo_switch_bathroom_r"}
  condition:
    condition: time
    after: '07:30:00'
    before: '22:30:00'
  action:
    - service: scene.turn_on
      entity_id: scene.bathroom_r_day

- alias: Bathroom | Duo switch | R | Off
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "off", "entity_id": "switch.duo_switch_bathroom_r"}
  action:
    - service: light.turn_off
      entity_id: light.hue_bulb_bathroom_r
