- alias: Bathroom | Duo switch | right | On
  initial_state: True
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "on", "entity_id": "switch.duo_switch_bathroom_r"}
  action:
    - service: homeassistant.turn_on
      entity_id: light.hue__bulb__bathroom__r


- alias: Bathroom | Duo switch | right | Off
  initial_state: True
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "off", "entity_id": "switch.duo_switch_bathroom_r"}
  action:
    - service: homeassistant.turn_off
      entity_id: light.hue__bulb__bathroom__r
