- alias: Bathroom | Duo switch | left | On
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "on", "entity_id": "switch.duo_switch_bathroom_l"}
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Bathroom"
        scene_name: "Bathroom | L | Relax"


- alias: Bathroom | Duo switch | left | Off
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "off", "entity_id": "switch.duo_switch_bathroom_l"}
  action:
    - service: homeassistant.turn_off
      entity_id: light.hue_candle_bathroom_l
