- alias: Bathroom | Duo switch | left | On
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "on", "entity_id": "switch.duo_switch_bathroom_l"}
  action:
    - service: homeassistant.turn_on
      entity_id: light.hue__candle__bathroom__l


- alias: Bathroom | Duo switch | left | Off
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "off", "entity_id": "switch.duo_switch_bathroom_l"}
  action:
    - service: homeassistant.turn_off
      entity_id: light.hue__candle__bathroom__l
