- alias: Bathroom | Duo switch | right | On
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "on", "entity_id": "switch.duo_switch_bathroom_r"}
  action:
    - service: homeassistant.turn_on
      entity_id: light.hue_bulb_bathroom_r
      brightness: 254
      rgb_color: 255,207,120


- alias: Bathroom | Duo switch | right | Off
  trigger:
    platform: event
    event_type: button_pressed
    event_data: {"state": "off", "entity_id": "switch.duo_switch_bathroom_r"}
  action:
    - service: homeassistant.turn_off
      entity_id: light.hue_bulb_bathroom_r
