- alias: "Bathroom | Time | Lights off"
  trigger:
    - platform: state
      entity_id: light.hue__candle__bathroom__l
      to: 'on'
      for:
        hours: 0
        minutes: 45
    - platform: state
      entity_id: light.hue__bulb__bathroom__r
      to: 'on'
      for:
        hours: 0
        minutes: 45
  action:
    - service: homeassistant.turn_off
      entity_id: light.bathroom
    - service: notify.matrix_notify
      data:
        message: "Shame! You forgot the Bathroom lights again!"
