homeassistant:
  customize: !include customize.yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key

fan:
  - platform: xiaomi_miio
    host: !secret sa_air_purifier_ip
    token: !secret sa_air_purifier_token