homeassistant:
  customize: !include customize.yaml

pi_hole:
  - host: !secret pihole_ip

transmission:
  host: !secret synology_ip
  username: !secret transmission_user
  password: !secret transmission_pass

speedtestdotnet:
  scan_interval:
    hours: 6
  monitored_conditions:
    - ping
    - download
    - upload

synology_dsm:
  host: !secret synology_ip
  username: !secret synology_username
  password: !secret synology_password
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - network_up
    - network_down
    - disk_smart_status
    - disk_status
    - disk_exceed_bad_sector_thr
    - disk_below_remain_life_thr
    - volume_status
    - volume_size_total
    - volume_size_used
    - volume_percentage_used
