homeassistant:
  customize: !include customize.yaml

pi_hole:
  - host: !secret pihole_ip

transmission:
  host: !secret transmission_location
  username: !secret transmission_user
  password: !secret transmission_pass

speedtestdotnet:
  scan_interval:
    hours: 6
  monitored_conditions:
    - ping
    - download
    - upload

synology_dsm:
  host: !secret synology_host
  username: !secret synology_username
  password: !secret synology_password
