homeassistant:
  customize: !include customize.yaml

pi_hole:
  - host: !secret pihole_host
    ssl: true
    verify_ssl: true
    api_key: !secret pihole_api

transmission:
  host: !secret transmission_host
  username: !secret transmission_user
  password: !secret transmission_pass

speedtestdotnet:
  scan_interval:
    hours: 6
  monitored_conditions:
    - ping
    - download
    - upload

# Again stuff moving to UI config only.
# synology_dsm:
#   host: !secret synology_host
#   username: !secret synology_username
#   password: !secret synology_password
#   ssl: true
#   verify_ssl: true
