homeassistant:
  customize: !include customize.yaml

transmission:
  host: !secret synology_ip
  username: !secret transmission_user
  password: !secret transmission_pass

speedtestdotnet:
  scan_interval:
    hours: 6
  monitored_conditions:
    - ping
    - download
    - upload

sensor: !include sensor.yaml
