- alias: Kitchen | Darkness cutoff | On
  trigger:
    platform: time_pattern
    minutes: '/5'
    seconds: 00
  condition:
    condition: numeric_state
    entity_id: sensor.illumination_in_kitchen
    below: 23
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.kitchen_meets_darkness_cutoff


- alias: Kitchen | Darkness cutoff | Off
  trigger:
    platform: time_pattern
    minutes: '/5'
    seconds: 00
  condition:
    condition: numeric_state
    entity_id: sensor.illumination_in_kitchen
    above: 23
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.kitchen_meets_darkness_cutoff
