- platform: scrape
  resource: !secret gas_station_1_url
  name: Gas station 1 Euro95
  select: 'tr + tr + tr'
  value_template: '{{ ((value.split("€")[1]) | replace(",", ".")) }}'
  unit_of_measurement: "€"
  scan_interval: 1800

- platform: scrape
  resource: !secret gas_station_2_url
  name: Gas station 2 Euro95
  select: 'div.station-price .station-price-content:first-child .price'
  value_template: '{{ ((value.split("€")[1]) | replace(",", ".")) }}'
  unit_of_measurement: "€"
  scan_interval: 1800

- platform: scrape
  resource: !secret gas_station_2_url
  name: Gas station 2 BlueOne
  select: 'div.station-price .station-price-content:nth-child(2) .price'
  value_template: '{{ ((value.split("€")[1]) | replace(",", ".")) }}'
  unit_of_measurement: "€"
  scan_interval: 1800
