# Temperature sensor
- platform: rest
  resource: !secret hallway_door_temp_url
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Temperature in hallway/door'

# Temperature sensor
- platform: rest
  resource: !secret hallway_stairs_temp_url
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Temperature in hallway/stairs'

# Temperature sensor
- platform: rest
  resource: !secret sitting_area_temp_url
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Temperature in sitting area'

# Temperature sensor
- platform: rest
  resource: !secret kitchen_temp_url
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Temperature in kitchen'

# Temperature sensor
- platform: rest
  resource: !secret corridor_temp_url
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Temperature in corridor'
