# Lightlevel sensor
- platform: rest
  resource: !secret hallway_door_lux_url
  value_template: '{{ value_json.config.battery }}'
  unit_of_measurement: '%'
  name: 'Motion hallway/door battery status'

# Lightlevel sensor
- platform: rest
  resource: !secret hallway_stairs_lux_url
  value_template: '{{ value_json.config.battery }}'
  unit_of_measurement: '%'
  name: 'Motion hallway/stairs battery status'

# Lightlevel sensor
- platform: rest
  resource: !secret sitting_area_lux_url
  value_template: '{{ value_json.config.battery }}'
  unit_of_measurement: '%'
  name: 'Motion sitting area battery status'

# Lightlevel sensor
- platform: rest
  resource: !secret kitchen_lux_url
  value_template: '{{ value_json.config.battery }}'
  unit_of_measurement: '%'
  name: 'Motion kitchen battery status'

# Lightlevel sensor
- platform: rest
  resource: !secret corridor_lux_url
  value_template: '{{ value_json.config.battery }}'
  unit_of_measurement: '%'
  name: 'Motion corridor battery status'
