- platform: miflora
  mac: !secret monstera_deliciosa_miflora_mac
  name: Monstera
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery


- platform: miflora
  mac: !secret musa_basjoo_miflora_mac
  name: Musa Basjoo
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
