- platform: miflora
  mac: !secret monstera_deliciosa_miflora_mac
  name: Monstera Deliciosa
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery


- platform: miflora
  mac: !secret cocos_nucifera_miflora_mac
  name: Cocos Nucifera
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery


- platform: miflora
  mac: !secret sabal_minor_mac
  name: Sabal Minor
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
