# Lightlevel sensor
- platform: rest
  resource: !secret sitting_area_lux_url
  # value_template: '{{ value_json.state.lightlevel }}'
  value_template: '{{ (10 ** (float(value_json.state.lightlevel - 1) / 10000))|round(1) }}'
  unit_of_measurement: Lux
  name: 'Illumination in sitting area'
