# Lightlevel sensor
- platform: rest
  resource: !secret hallway_door_lux_url
  value_template: '{{ (10 ** (float(value_json.state.lightlevel - 1) / 10000))|round(1) }}'
  unit_of_measurement: Lux
  name: 'Illumination in hallway/door'

# Temperature sensor
- platform: rest
  resource: !secret hallway_door_temp_url
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Temperature in hallway/door'
