- alias: Trigger sa media status override with button
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {"state": "on", "entity_id": "switch.programmable_one"}
    - platform: event
      event_type: button_pressed
      event_data: {"state": "off", "entity_id": "switch.programmable_one"}
  action:
    service_template: >
      {% if trigger.event.data.state == 'on' %}
        input_boolean.turn_on
      {% elif trigger.event.data.state == 'off' %}
        input_boolean.turn_off
      {% endif %}
    data:
      entity_id: input_boolean.sa_media_status_override
