- alias: Turn on the corridor light when there is movement and it's dark
  trigger:
    - platform: state
      entity_id: sensor.motion_in_corridor
      state: '1'
    - platform: state
      entity_id: sensor.motion_in_corridor
      state: '1'
  condition:
    condition: numeric_state
    entity_id: sensor.illumination_in_corridor
    below: 18
  action:
    - service: homeassistant.turn_on
      entity_id: light.corridor

- alias: Turn off the corridor light 5 minutes after last movement
  trigger:
    - platform: state
      entity_id: sensor.motion_in_corridor
      state: '0'
      for:
        minutes: 0
    - platform: state
      entity_id: sensor.motion_in_corridor
      state: '0'
      for:
        minutes: 0
  action:
    - service: homeassistant.turn_off
      entity_id: light.corridor
