- alias: Turn on the living room lights when there is movement
  trigger:
    platform: state
    entity_id: sensor.motion_in_sitting_area
    state: '1'
  action:
    service: homeassistant.turn_on
    entity_id: light.living_room

- alias: Turn off the living room lights 2 minutes after last movement
  trigger:
    platform: state
    entity_id: sensor.motion_in_sitting_area
    state: '0'
    for:
      minutes: 5
  action:
    service: homeassistant.turn_off
    entity_id: light.living_room

