media_player: !include media_player.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include boolean.yaml
automation: !include automation.yaml

cast:
  chromecast:
  - host: 10.0.221.26
  chromecast_audio:
  - host: 10.0.221.29
