rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A11D2A5T-if00-port0

binary_sensor: !include binary_sensor.yaml
light: !include light.yaml
switch: !include switch.yaml
cover: !include cover.yaml
