# - id: rfx_001
#   alias: rfx_001
#   trigger:
#     - platform: event
#       event_type: button_pressed
#       event_data: {"state": "on", "entity_id": "switch.power_socket_one"}
#     - platform: event
#       event_type: button_pressed
#       event_data: {"state": "off", "entity_id": "switch.power_socket_one"}
#     - platform: event
#       event_type: button_pressed
#       event_data: {"state": "on", "entity_id": "switch.power_socket_two"}
#     - platform: event
#       event_type: button_pressed
#       event_data: {"state": "off", "entity_id": "switch.power_socket_two"}
#     - platform: event
#       event_type: button_pressed
#       event_data: {"state": "on", "entity_id": "switch.power_socket_three"}
#     - platform: event
#       event_type: button_pressed
#       event_data: {"state": "off", "entity_id": "switch.power_socket_three"}
#   action:
#     service_template: >
#       {% if trigger.event.data.state == 'on' %}
#         switch.turn_on
#       {% elif trigger.event.data.state == 'off' %}
#         switch.turn_off
#       {% endif %}
#     data_template:
#       entity_id: >
#         {% if trigger.event.data.entity_id == 'switch.power_socket_one' %}
#           switch.0x000d6ffffedad23c_switch
#         {% elif trigger.event.data.entity_id == 'switch.power_socket_two' %}
#           switch.0x000d6ffffea6df64_switch
#         {% elif trigger.event.data.entity_id == 'switch.power_socket_three' %}
#           switch.0x000d6ffffea6e967_switch
#         {% endif %}
