webhook:
zigbee2mqtt_networkmap:

panel_iframe:
 networkmap:
   title: 'Zigbee Map'
   url: '/local/community/zigbee2mqtt_networkmap/map.html'
   icon: 'mdi:graphql'

automation: !include automation.yaml
