- platform: "mqtt"
  state_topic: "zigbee2mqtt/0x000b3cfffefab3f6"
  availability_topic: "zigbee2mqtt/bridge/state"
  brightness: true
  schema: "json"
  command_topic: "zigbee2mqtt/0x000b3cfffefab3f6/set"
