# - platform: "mqtt"
#   state_topic: "zigbee2mqtt/0x000b3cfffefab3f6"
#   availability_topic: "zigbee2mqtt/bridge/state"
#   brightness: true
#   schema: "json"
#   command_topic: "zigbee2mqtt/0x000b3cfffefab3f6/set"

# # Tradfri Backyard
# - platform: "mqtt"
#   state_topic: "zigbee2mqtt/0x000b57fffee35b50"
#   availability_topic: "zigbee2mqtt/bridge/state"
#   brightness: true
#   schema: "json"
#   command_topic: "zigbee2mqtt/0x000b57fffee35b50/set"

# # Tradfri Master bedroom
# - platform: "mqtt"
#   state_topic: "zigbee2mqtt/0x086bd7fffe2b8f58"
#   availability_topic: "zigbee2mqtt/bridge/state"
#   brightness: true
#   schema: "json"
#   command_topic: "zigbee2mqtt/0x086bd7fffe2b8f58/set"

# # Tradfri Front porch
- platform: "mqtt"
  state_topic: "zigbee2mqtt/0x086bd7fffe035d36"
  availability_topic: "zigbee2mqtt/bridge/state"
  brightness: true
  schema: "json"
  command_topic: "zigbee2mqtt/0x086bd7fffe035d36/set"
