# Sensor for monitoring the bridge state
- platform: mqtt
  name: Zigbee2mqtt Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless
# Sensor for Showing the Zigbee2mqtt Version
- platform: mqtt
  name: Zigbee2mqtt Version
  state_topic: "zigbee2mqtt/bridge/config"
  value_template: "{{ value_json.version }}"
  icon: mdi:zigbee
# Sensor for Showing the Coordinator Version
- platform: mqtt
  name: Coordinator Version
  state_topic: "zigbee2mqtt/bridge/config"
  value_template: "{{ value_json.coordinator }}"
  icon: mdi:chip

- platform: "mqtt"
  state_topic: "zigbee2mqtt/0x000b3cfffefab3f6"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: "{{ value_json.linkquality }}"

- platform: "mqtt"
  state_topic: "zigbee2mqtt/0x000b57fffee35b50"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: "{{ value_json.linkquality }}"
