- alias: SA | Motion | Christmas Tree Off
  trigger:
    platform: time
    minutes: '/10'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.motion_in_sitting_area
        state: '0'
      - condition: state
        entity_id: sensor.motion_in_kitchen
        state: '0'
  action:
    - service: switch.turn_off
      entity_id: switch.power_socket_two
    - service: light.turn_off
      entity_id: light.dimmable_socket_one