- alias: SA | Time | Lights off
  trigger:
    platform: time
    minutes: '/5'
    seconds: 00
  condition:
    condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: sensor.motion_in_sitting_area
            state: '0'
          - condition: state
            entity_id: binary_sensor.motion_sensor_sa
            state: 'off'
      - condition: state
        entity_id: sensor.motion_in_sitting_area
        state: '0'
      - condition: state
        entity_id: input_boolean.sa_meets_darkness_cutoff
        state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: light.sitting_area
    - service: homeassistant.turn_off
      entity_id: light.ledstrip_tv_cabinet
