- alias: SA | No Media
  trigger:
    - platform: state
      entity_id: binary_sensor.sa_motion_detected
      to: 'on'
    - platform: state
      entity_id: binary_sensor.sa_tv_media_playing
      to: 'off'
    - platform: time_pattern
      minutes: '/5'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.sa_motion_detected
        state: 'on'
      - condition: state
        entity_id: binary_sensor.sa_dark_enough
        state: 'on'
      - condition: state
        entity_id: binary_sensor.sa_tv_media_playing
        state: 'off'
  action:
    service: script.turn_on
    entity_id: script.scene_not_watching_tv


- alias: SA | Media Playing | State two
  trigger:
    - platform: state
      entity_id: binary_sensor.sa_motion_detected
      to: 'on'
    - platform: state
      entity_id: binary_sensor.sa_tv_media_playing
      to: 'on'
    - platform: time_pattern
      minutes: '/5'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.sa_motion_detected
        state: 'on'
      - condition: state
        entity_id: binary_sensor.sa_dark_enough
        state: 'on'
      - condition: state
        entity_id: binary_sensor.sa_tv_media_playing
        state: 'on'
      - condition: time
        after: '20:00:00'
        before: '05:00:00'
  action:
    service: script.turn_on
    entity_id: script.scene_watching_tv
