- alias: SA | No Media
  trigger:
    - platform: state
      entity_id: sensor.motion_in_sitting_area
      to: '1'
    - platform: state
      entity_id: input_boolean.sa_tv_media_playing
      to: 'off'
    - platform: time
      minutes: '/5'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.motion_in_sitting_area
        state: '1'
      - condition: state
        entity_id: input_boolean.sa_meets_darkness_cutoff
        state: 'on'
      - condition: state
        entity_id: input_boolean.sa_tv_media_playing
        state: 'off'
  action:
    service: script.turn_on
    entity_id: script.scene_not_watching_tv


- alias: SA | Media Playing | State one
  trigger:
    - platform: state
      entity_id: sensor.motion_in_sitting_area
      to: '1'
    - platform: state
      entity_id: input_boolean.sa_tv_media_playing
      to: 'on'
    - platform: time
      minutes: '/5'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.motion_in_sitting_area
        state: '1'
      - condition: state
        entity_id: input_boolean.sa_meets_darkness_cutoff
        state: 'on'
      - condition: state
        entity_id: input_boolean.sa_tv_media_playing
        state: 'on'
      - condition: time
        before: '20:00:00'
        after: '05:00:00'
  action:
    service: script.turn_on
    entity_id: script.scene_not_watching_tv


- alias: SA | Media Playing | State two
  trigger:
    - platform: state
      entity_id: sensor.motion_in_sitting_area
      to: '1'
    - platform: state
      entity_id: input_boolean.sa_tv_media_playing
      to: 'on'
    - platform: time
      minutes: '/5'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.motion_in_sitting_area
        state: '1'
      - condition: state
        entity_id: input_boolean.sa_meets_darkness_cutoff
        state: 'on'
      - condition: state
        entity_id: input_boolean.sa_tv_media_playing
        state: 'on'
      - condition: time
        after: '20:00:00'
        before: '05:00:00'
  action:
    service: script.turn_on
    entity_id: script.scene_watching_tv
