- alias: SA | State | Lights off
  trigger:
    - platform: state
      entity_id: binary_sensor.sa_motion_detected
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.sa_dark_enough
      to: 'off'
      for:
        minutes: 5
  action:
    - service: homeassistant.turn_off
      entity_id: light.sitting_area
    - service: homeassistant.turn_off
      entity_id: light.ledstrip_tv_cabinet
    - service: homeassistant.turn_off
      entity_id: light.ledstrip_black_cabinet
