- alias: SA | Time | Lights off
  trigger:
    platform: time_pattern
    minutes: '/1'
    seconds: 00
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.sa_motion_detected
        state: 'off'
        for:
          minutes: 5
      - condition: state
        entity_id: binary_sensor.sa_dark_enough
        state: 'off'
        for:
          minutes: 3
  action:
    - service: homeassistant.turn_off
      entity_id: light.sitting_area
    - service: homeassistant.turn_off
      entity_id: light.ledstrip_tv_cabinet
    - service: homeassistant.turn_off
      entity_id: light.ledstrip_black_cabinet
