- alias: SA | Chromecast playing | Dark | Scene on
  trigger:
    platform: state
    entity_id: media_player.living_room
    to: 'playing'
  condition:
    condition: numeric_state
    entity_id: sensor.illumination_in_sitting_area
    below: 18
  action:
    service: scene.turn_on
    entity_id: scene.sitting_area_watching_tv


- alias: SA | Kodi playing | Dark | Scene on
  trigger:
    platform: state
    entity_id: media_player.kodi
    to: 'playing'
  condition:
    condition: numeric_state
    entity_id: sensor.illumination_in_sitting_area
    below: 18
  action:
    service: scene.turn_on
    entity_id: scene.sitting_area_watching_tv