- alias: SA | Media playing | Dim scene
  trigger:
    platform: state
    entity_id: input_boolean.sa_tv_media_playing
    to: 'on'
  condition:
    - condition: time
      after: '20:00:00'
      before: '05:00:00'
    - condition: state
      entity_id: input_boolean.sa_meets_darkness_cutoff
      state: 'on'
  action:
    service: script.turn_on
    entity_id: script.scene_watching_tv