- alias: SA | Media playing | Dim scene
  trigger:
    platform: state
    entity_id: input_boolean.sa_tv_media_playing
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.sa_meets_darkness_cutoff
    state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.sitting_area_watching_tv