- alias: SA | Motion | Dark | No Media | Scene on
  trigger:
    platform: state
    entity_id: sensor.motion_in_sitting_area
    to: '1'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.illumination_in_sitting_area
        below: 18
      - condition: or
        conditions:
          - condition: state
            entity_id: media_player.living_room
            state: 'paused'
          - condition: state
            entity_id: media_player.living_room
            state: 'idle'
  action:
    service: scene.turn_on
    entity_id: scene.sitting_area_not_watching_tv

