- alias: Turn on the sitting area lights when there is movement and it's dark
  trigger:
    platform: state
    entity_id: sensor.motion_in_sitting_area
    to: '1'
  condition:
    condition: numeric_state
    entity_id: sensor.illumination_in_sitting_area
    below: 18
  action:
    - service: homeassistant.turn_on
      entity_id: light.sitting_area
    - service: homeassistant.turn_on
      entity_id: light.ledstrip_tv_cabinet