- alias: Re-evaluate lighting in living room periodically and turn off accordingly
  trigger:
    platform: time
    minutes: '/5'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.motion_in_sitting_area
        state: '1'
      - condition: numeric_state
        entity_id: sensor.illumination_in_sitting_area
        above: 18
      - condition: state
        entity_id: light.living_room
        state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: light.living_room
    - service: homeassistant.turn_off
      entity_id: light.ledstrip_tv_cabinet