- alias: Re-evaluate lighting in sitting area periodically and turn on accordingly
  trigger:
    platform: time
    minutes: '/5'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.motion_in_sitting_area
        state: '1'
      - condition: numeric_state
        entity_id: sensor.illumination_in_sitting_area
        below: 18
      - condition: state
        entity_id: light.sitting_area
        state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: light.sitting_area
    - service: homeassistant.turn_on
      entity_id: light.ledstrip_tv_cabinet